createConditionOccurrenceTests <- function () {

  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, the inpatient_admissions PDX is used. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, pdx = '2500', svcdate = '2012-08-09', tsvcdat = '2012-08-12', dxver = '9', caseid = encounter$caseid, year = '2012')
  add_inpatient_admissions(enrolid=patient$enrolid, pdx = '0092', caseid = encounter$caseid, dxver = '9', year = '2012')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '198337', condition_type_concept_id = '38000199')
    
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has the same diagnosis code in outpatient_services and facility_header but in different positions, outpatient_services dx is prioritized. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_outpatient_services(enrolid=patient$enrolid, svcdate = '2012-10-16', tsvcdat = '2012-10-16', dx1 = '1024', fachdid = encounter$caseid, dxver = '9')
  add_facility_header(enrolid=patient$enrolid, svcdate = '2012-10-16', tsvcdat = '2012-10-16', dx9 = '1024', fachdid = encounter$caseid, dxver='9')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id='433706', condition_type_concept_id = '38000215')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has diagnosis in dx4 field in inpatient_services, condition_type_concept_id = 38000187. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-07-23', tsvcdat = '2012-07-23', dx4='57411', dxver='9')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '195587', condition_type_concept_id = '38000187')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has diagnosis in dx9 field in facility_header, condition_type_concept_id = 38000208. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, fachdid = encounter$caseid, admdate = '2012-07-23',  svcdate = '2012-07-23', tsvcdat = '2012-07-23', year = '2012')
  add_facility_header(enrolid=patient$enrolid, fachdid = encounter$caseid, svcdate = '2012-07-23', tsvcdat = '2012-07-23', dx9 = '4760', dxver = '9', year = '2012')
  expect_condition_occurrence(person_id=patient$person_id, condition_concept_id = '24970', condition_type_concept_id = '38000208')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-04-14', tsvcdat = '2012-04-14', dx1='57411', pdx='4760', revcode = '0450', dxver = '9')
  expect_visit_occurrence(person_id = patient$person_id, visit_concept_id = '9203')
  expect_condition_occurrence(person_id=patient$person_id, condition_concept_id = '195587', condition_type_concept_id = '38000215')
  expect_condition_occurrence(person_id=patient$person_id, condition_concept_id = '24970', condition_type_concept_id = '38000215')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-10-15', tsvcdat = '2012-10-17', pdx = 'V755', dxver='9')
  expect_procedure_occurrence(person_id = patient$person_id, procedure_concept_id = '4064909')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, pdx = 'E0152', svcdate = '2012-02-04', tsvcdat = '2012-02-08', dxver = '9')
  expect_observation(person_id = patient$person_id, observation_concept_id = '4117957')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-08-21', tsvcdat = '2012-08-25', pdx = 'V726', dxver='9')
  expect_measurement(person_id = patient$enrolid, measurement_concept_id = '4034850')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-08-09', tsvcdat = '2012-08-12', dx1='S42241S', dxver='0')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '438021')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-08-09', tsvcdat = '2012-08-12', dx1='V9001', dxver='0')
  expect_observation(person_id = patient$person_id, observation_concept_id = '437476')
  expect_no_condition_occurrence(person_id = patient$person_id, condition_concept_id = '4053838')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2015-12-31', dtstart = '2015-01-01')
  add_inpatient_services(enrolid=patient$enrolid, admdate= '2015-11-09', svcdate = '2015-11-09', tsvcdat = '2015-11-12', dx1='S42241S', dxver='')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '438021')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, admdate = '2012-08-09', svcdate = '2012-08-09', tsvcdat = '2012-08-12', dx1='V9001', dxver='')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '4053838', condition_source_concept_id = '44821630' )
 
  #This will test HIX-1274
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-07-01', tsvcdat = '2012-07-01', dx4='57411', dxver='9')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-08-02', tsvcdat = '2012-08-02', dx4='57411', dxver='9')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '195587', condition_type_concept_id = '38000187', condition_start_date = '2012-07-01')
  expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '195587', condition_type_concept_id = '38000187', condition_start_date = '2012-08-02')
  
  if (Sys.getenv("truvenType") == "MDCD")
  {
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "Patient has diagnosis in dx1 in ltc, condition_type_concept_id = 38000215. Id is PERSON_ID")
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    add_long_term_care(enrolid = patient$enrolid, dx1 = 'v901', dxver = '9', svcdate = '11-05-2012', tsvcdat = '11-10-2012')
    expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '4053838', condition_type_concept_id = '38000215')
  }
  
  if (Sys.getenv("truvenType") == "CCAE")
  {
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID")
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    add_health_risk_assessment(enrolid = patient$enrolid, survdate = '2012-03-12', cc_backpain = "1")
    expect_condition_occurrence(person_id = patient$person_id, condition_concept_id = '134736', condition_start_date = '2012-03-12', condition_end_date = NULL)
    
    patient <- createPatient()
    encounter <- createEncounter()  
    declareTest(id = patient$person_id, "Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID")
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    add_health_risk_assessment(enrolid = patient$enrolid, survdate = '2012-09-13', cc_asthma = '1')
    expect_condition_occurrence(person_id = patient$person_id, condition_source_value = 'CC_ASTHMA', condition_start_date = '2012-09-13')
    
  }
}
