createVisitOccurrenceTests <- function () {
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient with visit that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, caseid = encounter$caseid, svcdate='2011-12-05', tsvcdat='2012-01-06')
  expect_visit_occurrence(person_id=patient$person_id, visit_start_date = '2012-01-01', visit_end_date = '2012-01-06')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-03-21', tsvcdat = '2012-03-19')
  expect_visit_occurrence(person_id=patient$person_id, visit_start_date = '2012-03-21', visit_end_date = '2012-03-21')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-12-30', tsvcdat = '2013-01-08')
  expect_visit_occurrence(person_id=patient$person_id, visit_start_date = '2012-12-30', visit_end_date = '2012-12-31')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "service in inpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, svcdate='2012-04-12', tsvcdat = '2012-04-12', revcode = '0450')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-04-12', visit_end_date = '2012-04-12', visit_concept_id = '9203')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_outpatient_services(enrolid = patient$enrolid, svcdate = '2012-05-01', tsvcdat = '2012-05-01', revcode='0450')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date='2012-05-01', visit_end_date='2012-05-01', visit_concept_id='9203')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_outpatient_services(enrolid=patient$enrolid, svcdate = '2012-10-17', tsvcdat = '2012-10-20', revcode='0100')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date='2012-10-17', visit_end_date='2012-10-20', visit_concept_id='9201')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12')
  add_inpatient_services(enrolid=patient$enrolid, svcdate='2012-10-01', tsvcdat = '2012-10-05')
  visit_id <- lookup_visit_occurrence(fetchField = "visit_occurrence_id", person_id = patient$person_id, visit_start_date='2012-08-08')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-10-01',preceding_visit_occurrence_id = visit_id )
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12')
  add_inpatient_services(enrolid=patient$enrolid, svcdate='2012-10-01', tsvcdat = '2012-10-05')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date='2012-08-08', visit_end_date = '2012-08-12')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-10-01', visit_end_date = '2012-10-05')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-09-03', tsvcdat = '2012-09-03', revcode = '0450')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-09-03', tsvcdat = '2012-09-10', revcode = '0100')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-09-03', visit_end_date = '2012-09-03', visit_concept_id = '9203')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-09-03', visit_end_date = '2012-09-10', visit_concept_id = '9201')
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-05-15', tsvcdat = '2012-05-16')
  add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-05-16', tsvcdat = '2012-05-17')
  expect_visit_occurrence(person_id = patient$person_id, visit_start_date = )
  
  patient <- createPatient()
  encounter <- createEncounter()
  declareTest(id = patient$person_id, "Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.")
  add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
  add_inpatient_services(enrolid=patient$enrolid, svcdate = '2012-03-21', tsvcdat = '2012-03-19',dstatus = '01')
  expect_visit_occurrence(person_id=patient$person_id, visit_start_date = '2012-03-21', visit_end_date = '2012-03-21',discharge_to_concept_id = '8536' )
  
  if (Sys.getenv("truvenType") != "MDCD")
  {
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.")
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01', rx='0')
    add_outpatient_services(enrolid=patient$enrolid, fachdid = encounter$caseid, svcdate='2012-01-06', tsvcdat='2012-01-06')
    expect_no_visit_occurrence(person_id = patient$person_id)
    
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.")
    provider1 <- createProvider()
    provider2 <- createProvider()
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12', provid = provider1$provid, stdprov = '220')
    add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12', provid = provider2$provid, stdprov = '540')
    expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-08-08', visit_end_date = '2012-08-12')
  }

  if (Sys.getenv("truvenType") == "MDCD")
  {
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.")
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01', drugcovg = '0')
    add_outpatient_services(enrolid=patient$enrolid, fachdid = encounter$caseid, svcdate='2012-01-06', tsvcdat='2012-01-06')
    expect_no_visit_occurrence(patient$person_id)
    
    patient <- createPatient()
    encounter <- createEncounter()
    declareTest(id = patient$person_id, "Patient has two records in the same visit with different prov_id and provstd. Id is PERSON_ID.")
    provider1 <- createProvider()
    provider2 <- createProvider()
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12', prov_id = provider1$provid, stdprov = '220')
    add_inpatient_services(enrolid = patient$enrolid, svcdate = '2012-08-08', tsvcdat = '2012-08-12', prov_id = provider2$provid, stdprov = '540')
    expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-08-08', visit_end_date = '2012-08-12')
    
    patient <- createPatient()
    encounter <- createEncounter()
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    declareTest(id = patient$person_id, "Patient has two LTC claims where the end_date of the first is within one day of the start_date of the second, one visit created. Id is PERSON_ID.")
    add_long_term_care(enrolid = patient$enrolid, svcdate = '2012-06-18', tsvcdat = '2012-06-30', year = '2012')
    add_long_term_care(enrolid = patient$enrolid, svcdate = '2012-07-01', tsvcdat = '2012-07-31', year = '2012')
    expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-06-18', visit_end_date = '2012-07-31')
    
    patient <- createPatient()
    encounter <- createEncounter()
    add_enrollment_detail(enrolid=patient$enrolid, dtend = '2012-12-31', dtstart = '2012-01-01')
    declareTest(id = patient$person_id, "Patient has LTC claim where the end_date = the start_date. Id is PERSON_ID.")
    add_long_term_care(enrolid = patient$enrolid, svcdate = '2012-08-03', tsvcdat = '2012-08-03', year = '2012')
    expect_visit_occurrence(person_id = patient$person_id, visit_start_date = '2012-08-01', visit_end_date = '2012-08-31')
    
  }
}
