SELECT DISTINCT REPLACE(stcm.SOURCE_CODE,'.','') AS SOURCE_CODE, MIN(stcm.TARGET_CONCEPT_ID) TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP stcm
WHERE stcm.TARGET_VOCABULARY_ID = 8 /*RXNORM*/
      AND stcm.SOURCE_VOCABULARY_ID in (3,4,5) /*ICD9 procedure/CPT4/HCPCS*/ 
      AND stcm.PRIMARY_MAP = 'Y'
      AND (stcm.INVALID_REASON IS NULL or stcm.INVALID_REASON = '')
      AND GETDATE() BETWEEN stcm.VALID_START_DATE and stcm.VALID_END_DATE
GROUP BY REPLACE(stcm.SOURCE_CODE,'.','')
