CREATE EXTERNAL TABLE {sc}.CARE_SITE 
 ( 
	 CARE_SITE_ID BIGINT, 
	 CARE_SITE_NAME VARCHAR(255),
	 PLACE_OF_SERVICE_CONCEPT_ID INT,
	 LOCATION_ID BIGINT, 
	 CARE_SITE_SOURCE_VALUE VARCHAR(250), 
	 PLACE_OF_SERVICE_SOURCE_VALUE VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/CARE_SITE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.CDM_SOURCE
(
	CDM_SOURCE_NAME varchar(250),
	CDM_SOURCE_ABBREVIATION VARCHAR(250),
	CDM_HOLDER VARCHAR(250),
	SOURCE_DESCRIPTION varchar(max),
	SOURCE_DOCUMENTATION_REFERENCE varchar(250),
	CDM_ETL_REFERENCE varchar(250),
	SOURCE_RELEASE_DATE varchar(10),
	CDM_RELEASE_DATE varchar(10),
	CDM_VERSION VARCHAR(250),
	VOCABULARY_VERSION VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/CDM_SOURCE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.COHORT 
 ( 
	 COHORT_DEFINITION_ID BIGINT, 
	 SUBJECT_ID BIGINT,
	 COHORT_START_DATE DATE, 
	 COHORT_END_DATE DATE 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/COHORT/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.CONDITION_ERA 
 ( 
	 CONDITION_ERA_ID BIGINT,
	 PERSON_ID BIGINT, 
	 CONDITION_CONCEPT_ID INT, 
	 CONDITION_ERA_START_DATE DATE, 
	 CONDITION_ERA_END_DATE DATE, 
	 CONDITION_OCCURRENCE_COUNT INTEGER 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/CONDITION_ERA/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.CONDITION_OCCURRENCE 
 ( 
	 CONDITION_OCCURRENCE_ID BIGINT,
	 PERSON_ID BIGINT, 
	 CONDITION_CONCEPT_ID INT, 
	 CONDITION_START_DATE DATE,
	 CONDITION_START_DATETIME TIMESTAMP,
	 CONDITION_END_DATE DATE,
	 CONDITION_END_DATETIME TIMESTAMP,
	 CONDITION_TYPE_CONCEPT_ID INT, 
	 STOP_REASON  VARCHAR(20), 
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT,
	 VISIT_DETAIL_ID BIGINT,
	 CONDITION_STATUS_CONCEPT_ID	INT,
	 CONDITION_SOURCE_VALUE VARCHAR(250),
	 CONDITION_SOURCE_CONCEPT_ID	INT,
	 CONDITION_STATUS_SOURCE_VALUE	VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/CONDITION_OCCURRENCE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.COST 
(
	 COST_ID BIGINT, 
	 COST_EVENT_ID BIGINT, 
	 COST_DOMAIN_ID VARCHAR(20), 
	 COST_TYPE_CONCEPT_ID INT, 
	 CURRENCY_CONCEPT_ID INT, 
	 TOTAL_CHARGE DECIMAL(38,2), 
	 TOTAL_COST DECIMAL(38,2), 
	 TOTAL_PAID DECIMAL(38,2), 
	 PAID_BY_PAYER DECIMAL(38,2), 
	 PAID_BY_PATIENT DECIMAL(38,2), 
	 PAID_PATIENT_COPAY DECIMAL(38,2), 
	 PAID_PATIENT_COINSURANCE DECIMAL(38,2), 
	 PAID_PATIENT_DEDUCTIBLE DECIMAL(38,2), 
	 PAID_BY_PRIMARY DECIMAL(38,2), 
	 PAID_INGREDIENT_COST DECIMAL(38,2), 
	 PAID_DISPENSING_FEE DECIMAL(38,2), 
	 PAYER_PLAN_PERIOD_ID BIGINT, 
	 AMOUNT_ALLOWED DECIMAL(38,2), 
	 REVENUE_CODE_CONCEPT_ID INT, 
	 REVENUE_CODE_SOURCE_VALUE VARCHAR(50),
	 DRG_CONCEPT_ID INTEGER,
	 DRG_SOURCE_VALUE CHAR(3) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/COST/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.DEATH 
 ( 
	 PERSON_ID BIGINT, 
	 DEATH_DATE DATE, 
	 DEATH_DATETIME TIMESTAMP,
	 DEATH_TYPE_CONCEPT_ID INT, 
	 CAUSE_CONCEPT_ID  INT, 
	 CAUSE_SOURCE_VALUE  VARCHAR(250),
	 CAUSE_SOURCE_CONCEPT_ID INT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/DEATH/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.DEVICE_EXPOSURE 
 ( 
	 DEVICE_EXPOSURE_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 DEVICE_CONCEPT_ID INT, 
	 DEVICE_EXPOSURE_START_DATE DATE,
	 DEVICE_EXPOSURE_START_DATETIME	TIMESTAMP,
	 DEVICE_EXPOSURE_END_DATE DATE,
	 DEVICE_EXPOSURE_END_DATETIME	TIMESTAMP,
	 DEVICE_TYPE_CONCEPT_ID INT, 
	 UNIQUE_DEVICE_ID VARCHAR(250),
	 QUANTITY INTEGER,
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 VISIT_DETAIL_ID BIGINT, 
	 DEVICE_SOURCE_VALUE VARCHAR(250),
	 DEVICE_SOURCE_CONCEPT_ID INT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/DEVICE_EXPOSURE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.DOSE_ERA 
 (
	 DOSE_ERA_ID  BIGINT, 
	 PERSON_ID BIGINT, 
	 DRUG_CONCEPT_ID INT, 
	 UNIT_CONCEPT_ID INT,
	 DOSE_VALUE DECIMAL(38,2),
	 DOSE_ERA_START_DATE DATE, 
	 DOSE_ERA_END_DATE DATE
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/DOSE_ERA/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.DRUG_ERA 
 ( 
	 DRUG_ERA_ID  BIGINT,
	 PERSON_ID BIGINT, 
	 DRUG_CONCEPT_ID INT, 
	 DRUG_ERA_START_DATE DATE, 
	 DRUG_ERA_END_DATE DATE, 
	 DRUG_EXPOSURE_COUNT INTEGER,
	 GAP_DAYS INTEGER 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/DRUG_ERA/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');


CREATE EXTERNAL TABLE {sc}.DRUG_EXPOSURE 
 ( 
	 DRUG_EXPOSURE_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 DRUG_CONCEPT_ID INT, 
	 DRUG_EXPOSURE_START_DATE DATE,
	 DRUG_EXPOSURE_START_DATETIME	TIMESTAMP,
	 DRUG_EXPOSURE_END_DATE DATE,
	 DRUG_EXPOSURE_END_DATETIME TIMESTAMP,
	 VERBATIM_END_DATE DATE,
	 DRUG_TYPE_CONCEPT_ID INT, 
	 STOP_REASON  VARCHAR(20), 
	 REFILLS INTEGER, 
	 QUANTITY DECIMAL(38,2), 
	 DAYS_SUPPLY  INTEGER, 
	 SIG VARCHAR(8000), 
	 ROUTE_CONCEPT_ID INT,
	 LOT_NUMBER VARCHAR(250),
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 VISIT_DETAIL_ID BIGINT, 
	 DRUG_SOURCE_VALUE VARCHAR(250),
	 DRUG_SOURCE_CONCEPT_ID INT,
	 ROUTE_SOURCE_VALUE VARCHAR(250),
	 DOSE_UNIT_SOURCE_VALUE VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/DRUG_EXPOSURE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.FACT_RELATIONSHIP 
 ( 
	 DOMAIN_CONCEPT_ID_1 BIGINT, 
	 FACT_ID_1 BIGINT,
	 DOMAIN_CONCEPT_ID_2 BIGINT,
	 FACT_ID_2 BIGINT,
	 RELATIONSHIP_CONCEPT_ID BIGINT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/FACT_RELATIONSHIP/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.LOCATION 
 ( 
	 LOCATION_ID  BIGINT, 
	 ADDRESS_1 VARCHAR(250), 
	 ADDRESS_2 VARCHAR(250), 
	 CITY VARCHAR(250), 
	 STATE VARCHAR(2), 
	 ZIP VARCHAR(9), 
	 COUNTY VARCHAR(250), 
	 LOCATION_SOURCE_VALUE VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/LOCATION/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.MEASUREMENT 
 ( 
	 MEASUREMENT_ID  BIGINT, 
	 PERSON_ID BIGINT, 
	 MEASUREMENT_CONCEPT_ID INT, 
	 MEASUREMENT_DATE DATE, 
	 MEASUREMENT_DATETIME TIMESTAMP,
	 MEASUREMENT_TIME VARCHAR(10),
	 MEASUREMENT_TYPE_CONCEPT_ID	INT,
	 OPERATOR_CONCEPT_ID INT, 
	 VALUE_AS_NUMBER DECIMAL(38,2), 
	 VALUE_AS_CONCEPT_ID INT, 
	 UNIT_CONCEPT_ID INT, 
	 RANGE_LOW DECIMAL(38,2), 
	 RANGE_HIGH DECIMAL(38,2), 
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 VISIT_DETAIL_ID BIGINT, 
	 MEASUREMENT_SOURCE_VALUE VARCHAR(250), 
	 MEASUREMENT_SOURCE_CONCEPT_ID	INT,
	 UNIT_SOURCE_VALUE VARCHAR(250),
	 VALUE_SOURCE_VALUE VARCHAR(700)	
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/MEASUREMENT/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.METADATA 
(
	METADATA_CONCEPT_ID INTEGER,
	NAME VARCHAR(250),
	VALUE_AS_STRING VARCHAR(500),
	VALUE_AS_CONCEPT_ID INTEGER,
	METADATA_DATE DATE,
	METADATA_DATETIME VARCHAR(10) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/METADATA/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.NOTE 
 ( 
	 NOTE_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 NOTE_DATE DATE,
	 NOTE_DATETIME  TIMESTAMP,
	 NOTE_TYPE_CONCEPT_ID INT,
	 NOTE_TEXT VARCHAR(8000),
	 PROVIDER_ID  BIGINT,
	 VISIT_OCCURRENCE_ID BIGINT,
	 VISIT_DETAIL_ID BIGINT, 
	 NOTE_SOURCE_VALUE VARCHAR(250),
	 NOTE_CLASS_CONCEPT_ID INTEGER,
	 NOTE_TITLE VARCHAR(250),
	 ENCODING_CONCEPT_ID INTEGER,
	 LANGUAGE_CONCEPT_ID INTEGER 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/NOTE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.OBSERVATION 
 ( 
	 OBSERVATION_ID  BIGINT,
	 PERSON_ID BIGINT, 
	 OBSERVATION_CONCEPT_ID INT, 
	 OBSERVATION_DATE DATE, 
	 OBSERVATION_DATETIME TIMESTAMP,
	 OBSERVATION_TYPE_CONCEPT_ID	INT, 
	 VALUE_AS_NUMBER DECIMAL(38,2), 
	 VALUE_AS_STRING VARCHAR(500), 
	 VALUE_AS_CONCEPT_ID INT, 
	 QUALIFIER_CONCEPT_ID INT,
	 UNIT_CONCEPT_ID INT, 
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 VISIT_DETAIL_ID BIGINT, 
	 OBSERVATION_SOURCE_VALUE VARCHAR(250),
	 OBSERVATION_SOURCE_CONCEPT_ID	INT, 
	 UNIT_SOURCE_VALUE VARCHAR(250),
	 QUALIFIER_SOURCE_VALUE VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/OBSERVATION/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.OBSERVATION_PERIOD 
 ( 
	 OBSERVATION_PERIOD_ID BIGINT,
	 PERSON_ID BIGINT, 
	 OBSERVATION_PERIOD_START_DATE DATE,
	 OBSERVATION_PERIOD_END_DATE DATE,
	 PERIOD_TYPE_CONCEPT_ID INT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/OBSERVATION_PERIOD/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.PAYER_PLAN_PERIOD 
 ( 
	 PAYER_PLAN_PERIOD_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 PAYER_PLAN_PERIOD_START_DATE	DATE, 
	 PAYER_PLAN_PERIOD_END_DATE DATE, 
	 PAYER_CONCEPT_ID INTEGER,
	 PAYER_SOURCE_VALUE VARCHAR(50), 
	 PAYER_SOURCE_CONCEPT_ID INTEGER,
	 PLAN_CONCEPT_ID INTEGER,
	 PLAN_SOURCE_VALUE VARCHAR(50),
	 PLAN_SOURCE_CONCEPT_ID INTEGER,
	 SPONSOR_CONCEPT_ID INTEGER,
	 SPONSOR_SOURCE_VALUE VARCHAR(50),
	 SPONSOR_SOURCE_CONCEPT_ID INTEGER,
	 FAMILY_SOURCE_VALUE VARCHAR(50), 
	 STOP_REASON_CONCEPT_ID INTEGER,
	 STOP_REASON_SOURCE_VALUE VARCHAR(50),
	 STOP_REASON_SOURCE_CONCEPT_ID	INTEGER 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/PAYER_PLAN_PERIOD/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.PERSON 
 (
	 PERSON_ID BIGINT, 
	 GENDER_CONCEPT_ID INT, 
	 YEAR_OF_BIRTH  INTEGER, 
	 MONTH_OF_BIRTH  INTEGER, 
	 DAY_OF_BIRTH  INTEGER, 
	 BIRTH_DATETIME  TIMESTAMP,
	 RACE_CONCEPT_ID INT, 
	 ETHNICITY_CONCEPT_ID INT, 
	 LOCATION_ID  BIGINT, 
	 PROVIDER_ID  BIGINT, 
	 CARE_SITE_ID  BIGINT, 
	 PERSON_SOURCE_VALUE VARCHAR(250), 
	 GENDER_SOURCE_VALUE VARCHAR(250),
	 GENDER_SOURCE_CONCEPT_ID INT, 
	 RACE_SOURCE_VALUE VARCHAR(250), 
	 RACE_SOURCE_CONCEPT_ID INT, 
	 ETHNICITY_SOURCE_VALUE VARCHAR(250),
	 ETHNICITY_SOURCE_CONCEPT_ID	INT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/PERSON/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.PROCEDURE_OCCURRENCE 
 ( 
	 PROCEDURE_OCCURRENCE_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 PROCEDURE_CONCEPT_ID INT, 
	 PROCEDURE_DATE  DATE, 
	 PROCEDURE_DATETIME TIMESTAMP,
	 PROCEDURE_TYPE_CONCEPT_ID INT,
	 MODIFIER_CONCEPT_ID INT,
	 QUANTITY INTEGER, 
	 PROVIDER_ID  BIGINT, 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 VISIT_DETAIL_ID BIGINT, 
	 PROCEDURE_SOURCE_VALUE VARCHAR(250),
	 PROCEDURE_SOURCE_CONCEPT_ID	INT,
	 MODIFIER_SOURCE_VALUE VARCHAR(250) 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/PROCEDURE_OCCURRENCE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.PROVIDER 
 ( 
	 PROVIDER_ID  BIGINT,
	 PROVIDER_NAME  VARCHAR(255), 
	 NPI VARCHAR(20), 
	 DEA VARCHAR(20), 
	 SPECIALTY_CONCEPT_ID INT, 
	 CARE_SITE_ID  BIGINT, 
	 YEAR_OF_BIRTH  INTEGER,
	 GENDER_CONCEPT_ID INT,
	 PROVIDER_SOURCE_VALUE VARCHAR(250), 
	 SPECIALTY_SOURCE_VALUE VARCHAR(250),
	 SPECIALTY_SOURCE_CONCEPT_ID	INT, 
	 GENDER_SOURCE_VALUE VARCHAR(250),
	 GENDER_SOURCE_CONCEPT_ID INT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/PROVIDER/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.VISIT_DETAIL 
 ( 
	VISIT_DETAIL_ID BIGINT,
	PERSON_ID BIGINT,
	VISIT_DETAIL_CONCEPT_ID INTEGER,
	VISIT_DETAIL_START_DATE DATE,
	VISIT_DETAIL_START_DATETIME TIMESTAMP,
	VISIT_DETAIL_END_DATE DATE,
	VISIT_DETAIL_END_DATETIME TIMESTAMP,
	VISIT_DETAIL_TYPE_CONCEPT_ID INTEGER,
	PROVIDER_ID BIGINT,
	CARE_SITE_ID BIGINT,
	ADMITTING_SOURCE_CONCEPT_ID INTEGER,
	DISCHARGE_TO_CONCEPT_ID INTEGER,
	PRECEDING_VISIT_DETAIL_ID BIGINT,
	VISIT_DETAIL_SOURCE_VALUE VARCHAR(250),
	VISIT_DETAIL_SOURCE_CONCEPT_ID INTEGER,
	ADMITTING_SOURCE_VALUE VARCHAR(50),
	DISCHARGE_TO_SOURCE_VALUE VARCHAR(50),
	VISIT_DETAIL_PARENT_ID BIGINT,
	VISIT_OCCURRENCE_ID BIGINT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/VISIT_DETAIL/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.VISIT_OCCURRENCE 
 ( 
	 VISIT_OCCURRENCE_ID BIGINT, 
	 PERSON_ID BIGINT, 
	 VISIT_CONCEPT_ID INT, 
	 VISIT_START_DATE DATE,
	 VISIT_START_DATETIME TIMESTAMP,
	 VISIT_END_DATE  DATE,
	 VISIT_END_DATETIME TIMESTAMP,
	 VISIT_TYPE_CONCEPT_ID INT,
	 PROVIDER_ID  BIGINT,
	 CARE_SITE_ID  BIGINT, 
	 VISIT_SOURCE_VALUE VARCHAR(250),
	 VISIT_SOURCE_CONCEPT_ID INT,
	 ADMITTING_SOURCE_CONCEPT_ID	INTEGER,
	 ADMITTING_SOURCE_VALUE VARCHAR(250),
	 DISCHARGE_TO_CONCEPT_ID INTEGER,
	 DISCHARGE_TO_SOURCE_VALUE VARCHAR(250),
	 PRECEDING_VISIT_OCCURRENCE_ID	BIGINT 
)
STORED AS PARQUET
LOCATION 's3://{bucket}/{folder}/VISIT_OCCURRENCE/'
TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}._VERSION 
( 
	VERSION_ID INTEGER,
	VERSION_DATE DATE 
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/VERSION/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.concept
(
	concept_id INTEGER,
	concept_name VARCHAR(255),
	domain_id VARCHAR(20),
	vocabulary_id VARCHAR(20),
	concept_class_id VARCHAR(20),
	standard_concept VARCHAR(1),
	concept_code VARCHAR(50),
	valid_start_date DATE,
	valid_end_date DATE,
	invalid_reason VARCHAR(1)
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/CONCEPT/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');


CREATE EXTERNAL TABLE {sc}.concept_ancestor
(
	ancestor_concept_id INTEGER,
	descendant_concept_id INTEGER,
	min_levels_of_separation INTEGER,
	max_levels_of_separation INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/CONCEPT_ANCESTOR/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.concept_class
(
	concept_class_id VARCHAR(20),
	concept_class_name VARCHAR(255),
	concept_class_concept_id INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/CONCEPT_CLASS/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.concept_relationship
(
	concept_id_1 INTEGER,
	concept_id_2 INTEGER,
	relationship_id VARCHAR(20),
	valid_start_date DATE,
	valid_end_date DATE,
	invalid_reason VARCHAR(1)
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/CONCEPT_RELATIONSHIP/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.concept_synonym
(
	concept_id INTEGER,
	concept_synonym_name VARCHAR(1000),
	language_concept_id INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/CONCEPT_SYNONYM/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.domain
(
	domain_id VARCHAR(20),
	domain_name VARCHAR(255),
	domain_concept_id INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/DOMAIN/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.drug_strength
(
	drug_concept_id INTEGER,
	ingredient_concept_id INTEGER,
	amount_value DOUBLE PRECISION,
	amount_unit_concept_id INTEGER,
	numerator_value DOUBLE PRECISION,
	numerator_unit_concept_id INTEGER,
	denominator_value DOUBLE PRECISION,
	denominator_unit_concept_id INTEGER,
	box_size  INTEGER,
	valid_start_date DATE,
	valid_end_date DATE,
	invalid_reason VARCHAR(1)
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/DRUG_STRENGTH/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.relationship
(
	relationship_id VARCHAR(20),
	relationship_name VARCHAR(255),
	is_hierarchical VARCHAR(1),
	defines_ancestry VARCHAR(1),
	reverse_relationship_id VARCHAR(20),
	relationship_concept_id INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/RELATIONSHIP/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.source_to_concept_map
(
	source_code VARCHAR(255),
	source_concept_id INTEGER,
	source_vocabulary_id VARCHAR(20),
	source_code_description VARCHAR(255),
	target_concept_id INTEGER,
	target_vocabulary_id VARCHAR(20),
	valid_start_date DATE,
	valid_end_date DATE,
	invalid_reason VARCHAR(1)
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/SOURCE_TO_CONCEPT_MAP/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');

CREATE EXTERNAL TABLE {sc}.vocabulary
(
	vocabulary_id VARCHAR(20),
	vocabulary_name VARCHAR(255),
	vocabulary_reference VARCHAR(255),
	vocabulary_version VARCHAR(255),
	vocabulary_concept_id INTEGER
)
STORED AS PARQUET LOCATION 's3://{bucket}/{folder}/VOCABULARY/' TABLE PROPERTIES ('COMPRESSION_TYPE'='GZIP');