SELECT DISTINCT SOURCE_CODE collate Latin1_General_CS_AS, TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP
WHERE SOURCE_VOCABULARY_ID IN (11, 900)	
				AND TARGET_VOCABULARY_ID = 11
				AND PRIMARY_MAP = 'Y'
				AND (INVALID_REASON IS NULL or INVALID_REASON = '')
				AND GETDATE() BETWEEN VALID_START_DATE AND VALID_END_DATE