with a as
(
SELECT DISTINCT stcm.TARGET_CONCEPT_ID, 
		stcm.SOURCE_CODE,
       YEAR(VALID_START_DATE)		AS START_YEAR, 
       CASE 
           WHEN YEAR(VALID_END_DATE) = 2099 THEN 2099 
           ELSE (YEAR(VALID_END_DATE)-1)  /*shift years to match TRUVEN's version mapping*/
       END							AS END_YEAR
FROM SOURCE_TO_CONCEPT_MAP stcm
WHERE stcm.TARGET_VOCABULARY_ID = 40      /*DRG*/
      AND stcm.SOURCE_VOCABULARY_ID = 40
      AND stcm.PRIMARY_MAP = 'Y'
)

SELECT CONVERT(varchar, CONVERT(int, SOURCE_CODE)), TARGET_CONCEPT_ID, CONVERT(DATE, STR(START_YEAR)) STARTDATE, CONVERT(DATE, STR(END_YEAR)) ENDDATE
FROM a
      