{Source_to_Standard}
SELECT distinct SOURCE_CODE, TARGET_CONCEPT_ID, TARGET_DOMAIN_ID
FROM CTE_VOCAB_MAP
WHERE lower(SOURCE_VOCABULARY_ID) IN ('icd9cm')
AND TARGET_STANDARD_CONCEPT IS NOT NULL
AND (TARGET_INVALID_REASON IS NULL or TARGET_INVALID_REASON = '')