SELECT stcm.SOURCE_CODE, 
		stcm.TARGET_CONCEPT_ID
	FROM SOURCE_TO_CONCEPT_MAP stcm
	WHERE stcm.SOURCE_VOCABULARY_ID = 6
	AND stcm.TARGET_VOCABULARY_ID = 6
	AND stcm.PRIMARY_MAP = 'Y'
	AND (stcm.INVALID_REASON IS NULL or stcm.INVALID_REASON = '')
	AND GETDATE() BETWEEN stcm.VALID_START_DATE AND stcm.VALID_END_DATE
	AND SUBSTRING(RIGHT(stcm.SOURCE_CODE, 2),1,1) = '-'
