SELECT REPLACE(stcm.SOURCE_CODE, '.', '') AS SOURCE_CODE,
stcm.TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP stcm
WHERE stcm.TARGET_VOCABULARY_ID IN (3,4,5) /*ICD-9-Proc/CPT-4/HCPCS*/
AND stcm.SOURCE_VOCABULARY_ID IN (3,4,5) /*ICD-9-Proc/CPT-4/HCPCS*/
AND stcm.PRIMARY_MAP = 'Y'
AND stcm.INVALID_REASON IS NULL
AND GETDATE() BETWEEN stcm.VALID_START_DATE and stcm.VALID_END_DATE	
AND stcm.SOURCE_CODE NOT IN (
/*Get Rid of CPT Modifiers*/
SELECT SOURCE_CODE
FROM SOURCE_TO_CONCEPT_MAP stcm 
WHERE stcm.SOURCE_VOCABULARY_ID = 4 
AND LEN(SOURCE_CODE) = 2 
)