SELECT * 
INTO  [CONCEPT]
FROM [{0}].[{1}].{sc}.[CONCEPT]

SELECT * 
INTO  [CONCEPT_ANCESTOR]
FROM [{0}].[{1}].{sc}.[CONCEPT_ANCESTOR]

SELECT * 
INTO  [CONCEPT_RELATIONSHIP]
FROM [{0}].[{1}].{sc}.[CONCEPT_RELATIONSHIP]

SELECT * 
INTO  [CONCEPT_SYNONYM]
FROM [{0}].[{1}].{sc}.[CONCEPT_SYNONYM]

SELECT * 
INTO  [RELATIONSHIP]
FROM [{0}].[{1}].{sc}.[RELATIONSHIP]

SELECT * 
INTO  [SOURCE_TO_CONCEPT_MAP]
FROM [{0}].[{1}].{sc}.[SOURCE_TO_CONCEPT_MAP]

SELECT * 
INTO  [VOCABULARY]
FROM [{0}].[{1}].{sc}.[VOCABULARY]