

---- create dimension constraints

ALTER TABLE {sc}.[VOCABULARY] ADD CONSTRAINT [PK_VOCABULARY] PRIMARY KEY CLUSTERED 
(
    [VOCABULARY_ID]
)
WITH (DATA_COMPRESSION = PAGE);
GO

--

ALTER TABLE {sc}.[RELATIONSHIP] ADD CONSTRAINT [PK_RELATIONSHIP] PRIMARY KEY CLUSTERED 
(
    [RELATIONSHIP_ID]
)
WITH (DATA_COMPRESSION = PAGE);
GO

--

ALTER TABLE {sc}.[CONCEPT] ADD CONSTRAINT [PK_CONCEPT] PRIMARY KEY CLUSTERED 
(
	[CONCEPT_ID] 
)
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XCOC_ID_LEV] ON {sc}.[CONCEPT] 
(
	[CONCEPT_ID] ASC,
	[DOMAIN_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XCON_2CD] ON {sc}.[CONCEPT] 
(
	[CONCEPT_CLASS_ID] ASC,
	[CONCEPT_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XCON_2ID] ON {sc}.[CONCEPT] 
(
	[VOCABULARY_ID] ASC,
	[CONCEPT_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XCON_3CD] ON {sc}.[CONCEPT] 
(
	[VOCABULARY_ID] ASC,
	[CONCEPT_CLASS_ID] ASC,
	[CONCEPT_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

--

ALTER TABLE {sc}.[CONCEPT_ANCESTOR] ADD CONSTRAINT [PK_CONCEPT_ANCESTOR] PRIMARY KEY CLUSTERED 
(
    [ANCESTOR_CONCEPT_ID],
    [DESCENDANT_CONCEPT_ID]
)
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [X_AN_AN] ON {sc}.[CONCEPT_ANCESTOR] 
(
	[ANCESTOR_CONCEPT_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [X_AN_D] ON {sc}.[CONCEPT_ANCESTOR] 
(
	[DESCENDANT_CONCEPT_ID] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[CONCEPT_ANCESTOR] WITH CHECK ADD CONSTRAINT [CONCEPT_ANCESTOR_FK] FOREIGN KEY([ANCESTOR_CONCEPT_ID])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO

ALTER TABLE {sc}.[CONCEPT_ANCESTOR] WITH CHECK ADD CONSTRAINT [CONCEPT_DESCENDANT_FK] FOREIGN KEY([DESCENDANT_CONCEPT_ID])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO

--

ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] ADD CONSTRAINT [PK_CONCEPT_RELATIONSHIP] PRIMARY KEY CLUSTERED 
(
    [CONCEPT_ID_1],
    [CONCEPT_ID_2],
    [RELATIONSHIP_ID]
)
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XID12] ON {sc}.[CONCEPT_RELATIONSHIP] 
(
	[CONCEPT_ID_1] ASC,
	[CONCEPT_ID_2] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [XID21] ON {sc}.[CONCEPT_RELATIONSHIP] 
(
	[CONCEPT_ID_2] ASC,
	[CONCEPT_ID_1] ASC
) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] WITH CHECK ADD CONSTRAINT [CONCEPT_REL_PARENT_FK] FOREIGN KEY([CONCEPT_ID_1])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO
ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] CHECK CONSTRAINT [CONCEPT_REL_PARENT_FK]
GO

ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] WITH CHECK ADD CONSTRAINT [CONCEPT_REL_CHILD_FK] FOREIGN KEY([CONCEPT_ID_2])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO
ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] CHECK CONSTRAINT [CONCEPT_REL_CHILD_FK]
GO

ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] WITH CHECK ADD CONSTRAINT [CONCEPT_REL_REL_TYPE_FK] FOREIGN KEY([RELATIONSHIP_ID])
REFERENCES {sc}.[RELATIONSHIP] ([RELATIONSHIP_ID])
GO
ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] CHECK CONSTRAINT [CONCEPT_REL_REL_TYPE_FK]
GO

ALTER TABLE {sc}.[CONCEPT_RELATIONSHIP] ADD DEFAULT ('12/31/2099') FOR [VALID_END_DATE]
GO

--

ALTER TABLE {sc}.[CONCEPT_SYNONYM] WITH CHECK ADD CONSTRAINT [CONCEPT_SYNONYM_CONCEPT_FK] FOREIGN KEY([CONCEPT_ID])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO
ALTER TABLE {sc}.[CONCEPT_SYNONYM] CHECK CONSTRAINT [CONCEPT_SYNONYM_CONCEPT_FK]
GO

--


CREATE NONCLUSTERED INDEX [IX_TARGET_CONCEPT_ID] ON {sc}.[SOURCE_TO_CONCEPT_MAP]
(
	[TARGET_CONCEPT_ID] 
) 
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX IX_VOCAB_IDS ON {sc}.[SOURCE_TO_CONCEPT_MAP] 
(
    [TARGET_VOCABULARY_ID], [SOURCE_VOCABULARY_ID]
)
INCLUDE ([SOURCE_CODE], [TARGET_CONCEPT_ID])
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX IX_SOURCECODE_TARGET_SOURCE ON {sc}.[SOURCE_TO_CONCEPT_MAP] 
(
    [SOURCE_CODE], [TARGET_VOCABULARY_ID], [SOURCE_VOCABULARY_ID]
)
INCLUDE ([TARGET_CONCEPT_ID])
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[SOURCE_TO_CONCEPT_MAP] WITH CHECK ADD CONSTRAINT [SOURCE_TO_CONCEPT_CONCEPT] FOREIGN KEY([TARGET_CONCEPT_ID])
REFERENCES {sc}.[CONCEPT] ([CONCEPT_ID])
GO
ALTER TABLE {sc}.[SOURCE_TO_CONCEPT_MAP] CHECK CONSTRAINT [SOURCE_TO_CONCEPT_CONCEPT]
GO

ALTER TABLE {sc}.[SOURCE_TO_CONCEPT_MAP] WITH CHECK ADD CONSTRAINT [SOURCE_TO_CONCEPT_SOURCE_VOCAB] FOREIGN KEY([SOURCE_VOCABULARY_ID])
REFERENCES {sc}.[VOCABULARY] ([VOCABULARY_ID])
GO
ALTER TABLE {sc}.[SOURCE_TO_CONCEPT_MAP] CHECK CONSTRAINT [SOURCE_TO_CONCEPT_SOURCE_VOCAB]
GO

ALTER TABLE {sc}.[LOCATION] ADD CONSTRAINT [PK_LOCATION] PRIMARY KEY CLUSTERED 
(
    [LOCATION_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [LOCATION_SOURCE_VALUE_IDX] ON {sc}.[LOCATION]
(
	[LOCATION_SOURCE_VALUE] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

--

ALTER TABLE {sc}.[PROVIDER] ADD CONSTRAINT [PROVIDER_PK] PRIMARY KEY CLUSTERED 
(
    [PROVIDER_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO


ALTER TABLE {sc}.[PERSON] ADD CONSTRAINT [PK_PERSON] PRIMARY KEY CLUSTERED 
(
    [PERSON_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[PERSON]  WITH CHECK ADD  CONSTRAINT [PERSON_LOCATION_FK] FOREIGN KEY([LOCATION_ID])
REFERENCES {sc}.[LOCATION] ([LOCATION_ID])
GO

ALTER TABLE {sc}.[PERSON]  WITH CHECK ADD  CONSTRAINT [PERSON_PROVIDER_FK] FOREIGN KEY([PROVIDER_ID])
REFERENCES {sc}.[PROVIDER] ([PROVIDER_ID])
GO


ALTER TABLE {sc}.[VISIT_OCCURRENCE]  WITH CHECK ADD  CONSTRAINT [VISIT_OCCURRENCE_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_VISIT_OCCURRENCE_PERSON_ID] ON {sc}.[VISIT_OCCURRENCE]
(
	[PERSON_ID] ASC,
	[VISIT_OCCURRENCE_ID] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_VISIT_OCCURRENCE_VISIT_OCCURRENCE_ID] ON {sc}.[VISIT_OCCURRENCE]
(
	[VISIT_OCCURRENCE_ID] ASC
)
INCLUDE ( 	[VISIT_CONCEPT_ID],
	[VISIT_START_DATE],
	[VISIT_END_DATE]) 	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[PROCEDURE_OCCURRENCE] ADD CONSTRAINT [PK_PROCEDURE_OCCURRENCE] PRIMARY KEY NONCLUSTERED 
(
    [PROCEDURE_OCCURRENCE_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[PROCEDURE_OCCURRENCE]  WITH CHECK ADD  CONSTRAINT [PROCEDURE_OCCURRENCE_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_PROCEDURE_OCCURRENCE_PERSON_ID] ON {sc}.[PROCEDURE_OCCURRENCE]
(
	[PERSON_ID] ASC,
	[PROCEDURE_OCCURRENCE_ID] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [IX_PROCEDURE_OCCURRENCE_PROCEDURE_CONCEPT_ID] ON {sc}.[PROCEDURE_OCCURRENCE]
(
	[PROCEDURE_CONCEPT_ID] ASC
)
INCLUDE ( [PROCEDURE_DATE] )
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[OBSERVATION]  WITH CHECK ADD  CONSTRAINT [OBSERVATION_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_OBSERVATION_PERIOD_PERSON_ID] ON {sc}.[OBSERVATION_PERIOD]
(
	[PERSON_ID] ASC,
	[OBSERVATION_PERIOD_START_DATE] ASC,
	[OBSERVATION_PERIOD_END_DATE] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE UNIQUE CLUSTERED INDEX [IX_OBSERVATION_PERSON_ID] ON {sc}.[OBSERVATION]
(
	[PERSON_ID] ASC,
	[OBSERVATION_ID] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [IX_OBSERVATION_OBSERVATION_CONCEPT_ID] ON {sc}.[OBSERVATION]
(
	[OBSERVATION_CONCEPT_ID] ASC
)
INCLUDE ( [OBSERVATION_DATE],
	[VALUE_AS_NUMBER],
	[VALUE_AS_STRING]) 	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO
--

ALTER TABLE {sc}.[DRUG_EXPOSURE] ADD CONSTRAINT [PK_DRUG_EXPOSURE] PRIMARY KEY NONCLUSTERED 
(
    [DRUG_EXPOSURE_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[DRUG_EXPOSURE]  WITH CHECK ADD  CONSTRAINT [DRUG_EXPOSURE_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_DRUG_EXPOSURE_PERSON_ID] ON {sc}.[DRUG_EXPOSURE]
(
	[PERSON_ID] ASC,
	[DRUG_EXPOSURE_ID] ASC
)	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [IX_DRUG_EXPOSURE_DRUG_CONCEPT_ID] ON {sc}.[DRUG_EXPOSURE]
(
	[DRUG_CONCEPT_ID] ASC
)
INCLUDE ( 	[DRUG_EXPOSURE_START_DATE],
	[DRUG_EXPOSURE_END_DATE],
	[REFILLS],
	[QUANTITY],
	[DAYS_SUPPLY]) 	
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[CONDITION_OCCURRENCE]  WITH CHECK ADD  CONSTRAINT [CONDITION_OCCURRENCE_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_CONDITION_OCCURRENCE_PERSON_ID] ON {sc}.[CONDITION_OCCURRENCE]
(
	[PERSON_ID] ASC,
	[CONDITION_OCCURRENCE_ID] ASC
)
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);

CREATE NONCLUSTERED INDEX [IX_CONDITION_OCCURRENCE_CONCEPT_ID] ON {sc}.[CONDITION_OCCURRENCE]
(
	[CONDITION_CONCEPT_ID] ASC
)
INCLUDE ( [CONDITION_START_DATE], [CONDITION_END_DATE] )
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);


ALTER TABLE {sc}.[CONDITION_ERA]  WITH CHECK ADD  CONSTRAINT [CONDITION_ERA_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_CONDITION_ERA_PERSON_ID] ON {sc}.[CONDITION_ERA]
(
	[PERSON_ID] ASC,
	[CONDITION_ERA_ID] ASC
)
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);

CREATE NONCLUSTERED INDEX [IX_CONDITION_ERA_CONDITION_CONCEPT_ID] ON {sc}.[CONDITION_ERA]
(
	[CONDITION_CONCEPT_ID] ASC
)
INCLUDE ( [CONDITION_ERA_START_DATE], [CONDITION_ERA_END_DATE] )
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

ALTER TABLE {sc}.[DEATH]  WITH CHECK ADD  CONSTRAINT [DEATH_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE CLUSTERED INDEX [PK_DEATH] ON {sc}.[DEATH]
(
	[PERSON_ID] ASC,
	[CAUSE_CONCEPT_ID] ASC
)
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO


REFERENCES {sc}.[DRUG_EXPOSURE] ([DRUG_EXPOSURE_ID])
GO

ALTER TABLE {sc}.[DRUG_ERA]  WITH CHECK ADD  CONSTRAINT [DRUG_ERA_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE UNIQUE CLUSTERED INDEX [IX_DRUG_ERA_PERSON_ID] ON {sc}.[DRUG_ERA]
(
	[PERSON_ID] ASC,
	[DRUG_ERA_ID] ASC
)
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE NONCLUSTERED INDEX [IX_DRUG_ERA_DRUG_CONCEPT_ID] ON {sc}.[DRUG_ERA]
(
	[DRUG_CONCEPT_ID] ASC
)
INCLUDE ( [DRUG_ERA_START_DATE], [DRUG_ERA_END_DATE] ) 
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO


REFERENCES {sc}.[PROCEDURE_OCCURRENCE] ([PROCEDURE_OCCURRENCE_ID])
GO
--

ALTER TABLE {sc}.[CARE_SITE] ADD CONSTRAINT [PK_CARE_SITE] PRIMARY KEY CLUSTERED 
(
    [CARE_SITE_ID] 
)	
WITH (DATA_COMPRESSION = PAGE);
GO

CREATE INDEX [COHORT_CONCEPT_ID] ON {sc}.[COHORT] 
( [COHORT_DEFINITION_ID] )
INCLUDE ([COHORT_START_DATE], [COHORT_END_DATE], [SUBJECT_ID])
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO

CREATE CLUSTERED INDEX [IX_COHORT_COHORT_CONCEPT_ID] ON {sc}.[COHORT]
(
	[COHORT_DEFINITION_ID] ASC,
	[SUBJECT_ID] ASC
)
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO


CREATE CLUSTERED INDEX [pk_payer_plan_period] ON {sc}.[PAYER_PLAN_PERIOD]
(
	[PERSON_ID] ASC
)
WITH (DATA_COMPRESSION = PAGE);

ALTER TABLE {sc}.[PAYER_PLAN_PERIOD]  WITH CHECK ADD  CONSTRAINT [PAYER_PLAN_PERIOD_PERSON_FK] FOREIGN KEY([PERSON_ID])
REFERENCES {sc}.[PERSON] ([PERSON_ID])
GO

CREATE INDEX IX_PERSON_ID_START ON {sc}.[PAYER_PLAN_PERIOD]
( 
    PERSON_ID 
)
INCLUDE ( PAYER_PLAN_PERIOD_START_DATE )
WITH (SORT_IN_TEMPDB = ON, DATA_COMPRESSION = PAGE);
GO