DECLARE @sql nvarchar(MAX)

IF (EXISTS (SELECT *
      FROM INFORMATION_SCHEMA.TABLES
      WHERE TABLE_SCHEMA = 'dbo'
      AND  TABLE_NAME = 'LONG_TERM_CARE'))

BEGIN
SET @sql = 
-- MDCD

'
WITH CTE_SUMMARY AS ( 
SELECT ENROLID, MIN(DOBYR) MIN_DOB, MAX(DOBYR) AS MAX_DOB, MIN(ed.SEX) AS MIN_SEX, MAX(ed.SEX) AS MAX_SEX 
  FROM ENROLLMENT_DETAIL ed 
  GROUP BY ENROLID 
)	

SELECT DISTINCT {0}
		z.ENROLID, z.ENROLID
	FROM ENROLLMENT_DETAIL z
	LEFT JOIN (
			SELECT ENROLID, 
				YEAR(MIN(DTSTART))	AS MIN_ENROLL_YEAR
			FROM ENROLLMENT_DETAIL
			GROUP BY ENROLID
		) m ON m.ENROLID = z.ENROLID
	WHERE z.ENROLID IS NOT NULL AND (DRUGCOVG = ''1'' OR MEDICARE = ''1'') AND z.DOBYR BETWEEN 1900 AND YEAR(GETDATE())
	AND z.DOBYR <= (m.MIN_ENROLL_YEAR+1) and z.ENROLID NOT IN (
		SELECT ENROLID
		FROM CTE_SUMMARY
		WHERE MIN_DOB != 0
		AND
		(
		MIN_SEX != MAX_SEX
		OR
		(
		MAX_DOB > (YEAR(GETDATE()) - 90) /*MDCD ONLY*/
		AND ABS(MIN_DOB-MAX_DOB) > 2
		))
	)
	'
END
ELSE
BEGIN
-- CCAE, MDCR
SET @sql = '
WITH CTE_SUMMARY AS ( 
SELECT ENROLID, MIN(DOBYR) MIN_DOB, MAX(DOBYR) AS MAX_DOB, MIN(ed.SEX) AS MIN_SEX, MAX(ed.SEX) AS MAX_SEX 
  FROM ENROLLMENT_DETAIL ed 
  GROUP BY ENROLID 
)	

SELECT DISTINCT {0}
		z.ENROLID, z.ENROLID
	FROM ENROLLMENT_DETAIL z
	LEFT JOIN (
			SELECT ENROLID, 
				YEAR(MIN(DTSTART))	AS MIN_ENROLL_YEAR
			FROM ENROLLMENT_DETAIL
			GROUP BY ENROLID
		) m ON m.ENROLID = z.ENROLID
	WHERE z.ENROLID IS NOT NULL AND z.RX = ''1'' AND z.DOBYR BETWEEN 1900 AND YEAR(GETDATE())
	AND z.DOBYR <= (m.MIN_ENROLL_YEAR+1) and z.ENROLID NOT IN (
		SELECT ENROLID 
	FROM CTE_SUMMARY 
	WHERE MIN_DOB != 0 AND ( 
		   ABS(MIN_DOB-MAX_DOB) > 2 
		   OR MIN_SEX != MAX_SEX 
	))'
END

EXECUTE sp_executesql @sql;