IF OBJECT_ID('cdm_testing_ccae.test_results', 'U') IS NOT NULL DROP TABLE cdm_testing_ccae.test_results;
CREATE TABLE cdm_testing_ccae.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- Test Case1: Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, the inpatient_admissions PDX is used. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, the inpatient_admissions PDX is used. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '1' AND condition_concept_id = '198337' AND condition_type_concept_id = '38000199') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case3: Patient has the same diagnosis code in outpatient_services and facility_header but in different positions, outpatient_services dx is prioritized. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header but in different positions, outpatient_services dx is prioritized. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '3' AND condition_concept_id = '433706' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case5: Patient has diagnosis in dx4 field in inpatient_services, condition_type_concept_id = 38000187. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 5 AS id, 'Patient has diagnosis in dx4 field in inpatient_services, condition_type_concept_id = 38000187. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '5' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case7: Patient has diagnosis in dx9 field in facility_header, condition_type_concept_id = 38000208. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 7 AS id, 'Patient has diagnosis in dx9 field in facility_header, condition_type_concept_id = 38000208. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '7' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000208') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case9: Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '9' AND visit_concept_id = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case11: Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '11' AND procedure_concept_id = '4064909') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case13: Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 13 AS id, 'Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '13' AND observation_concept_id = '4117957') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case15: Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 15 AS id, 'Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '15' AND measurement_concept_id = '4034850') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case17: Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 17 AS id, 'Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '17' AND condition_concept_id = '438021') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case19: patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '19' AND observation_concept_id = '437476') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '19' AND condition_concept_id = '4053838') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case21: Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 21 AS id, 'Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '21' AND condition_concept_id = '438021') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case23: Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 23 AS id, 'Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '23' AND condition_concept_id = '4053838' AND condition_source_concept_id = '44821630') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case25: Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-07-01' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-08-02' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case27: HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 27 AS id, 'HRA mapped to condition/drug the END_DATE is NULL. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '27' AND condition_concept_id = '134736' AND condition_start_date = '2012-03-12' AND condition_end_date IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case29: Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 29 AS id, 'Patient has 1 in CC_ASTHMA column, condition_source_value=Self-reported Asthma. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_occurrence WHERE person_id = '29' AND condition_start_date = '2012-09-13' AND condition_source_value = 'CC_ASTHMA') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case31: Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 31 AS id, 'Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_era WHERE person_id = '31') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case33: Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 33 AS id, 'Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_era WHERE person_id = '33' AND condition_era_start_date = '2012-07-01' AND condition_era_end_date = '2012-07-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case35: Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 35 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_era WHERE person_id = '35' AND condition_era_start_date = '2012-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 35 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.condition_era WHERE person_id = '35' AND condition_era_start_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case37: Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 37 AS id, 'Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Drug' AND total_cost = '20' AND paid_patient_copay = '20' AND paid_ingredient_cost = '50' AND paid_dispensing_fee = '25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case39: Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 39 AS id, 'Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '39' AND procedure_concept_id = '40757105' AND procedure_date = '2012-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 39 AS id, 'Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '160' AND paid_patient_copay = '40' AND paid_patient_deductible = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case41: Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 41 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '41' AND measurement_concept_id = '2212375' AND measurement_date = '2012-05-07') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 41 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Measurement' AND total_paid = '157' AND paid_by_payer = '120' AND paid_patient_copay = '37') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case43: Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 43 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '43' AND observation_concept_id = '2721503' AND observation_date = '2012-10-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 43 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Observation' AND paid_by_payer = '75' AND paid_patient_coinsurance = '100' AND paid_by_primary = '52') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case45: Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 45 AS id, 'Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '100' AND paid_patient_copay = '80' AND paid_patient_deductible = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case47: Testing DRG Populates (HIX-1431). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 47 AS id, 'Testing DRG Populates (HIX-1431). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '100' AND paid_patient_copay = '80' AND paid_patient_deductible = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case49: Patient has cost values, cost is correctly associated with the right event_id (HIX-1515).
INSERT INTO cdm_testing_ccae.test_results SELECT 49 AS id, 'Patient has cost values, cost is correctly associated with the right event_id (HIX-1515).' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_event_id = (SELECT procedure_occurrence_id FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '49')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case51: Patient has invalid revenue code, REVENUE_CODE_CONCEPT_ID set to 0. Id is PERSON_ID. (HIX-1486)
INSERT INTO cdm_testing_ccae.test_results SELECT 51 AS id, 'Patient has invalid revenue code, REVENUE_CODE_CONCEPT_ID set to 0. Id is PERSON_ID. (HIX-1486)' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.cost WHERE cost_event_id = (SELECT procedure_occurrence_id FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '51') AND revenue_code_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case53: Date of death visit end date. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 53 AS id, 'Date of death visit end date. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '53' AND death_date = '2013-01-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case55: ICD10 Death and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 55 AS id, 'ICD10 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '55' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case57: ICD9 Death and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 57 AS id, 'ICD9 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '57' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case59: Discharge Status and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 59 AS id, 'Discharge Status and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '59' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case61: Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 61 AS id, 'Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '61' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case63: Death and then contined Activity Cancels Death. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 63 AS id, 'Death and then contined Activity Cancels Death. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.death WHERE person_id = '63') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case65: Duplicate drug records become one record in the CDM. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 65 AS id, 'Duplicate drug records become one record in the CDM. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '65' AND drug_concept_id = '40161912' AND drug_exposure_start_date = '02-01-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case67: Negative daysupp should be 0 in cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 67 AS id, 'Negative daysupp should be 0 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '67' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '06-12-2012' AND days_supply = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case69: Daysupp >365 should be 365 in cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 69 AS id, 'Daysupp >365 should be 365 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '69' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '08-07-2012' AND days_supply = '365') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case71: CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 71 AS id, 'CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '71' AND drug_concept_id = '2213404' AND drug_exposure_start_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case73: Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 73 AS id, 'Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '73' AND drug_concept_id = '2213404' AND drug_exposure_start_date = '2012-08-09' AND drug_exposure_end_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case75: Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 75 AS id, 'Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '75' AND drug_concept_id = '46275250' AND drug_exposure_start_date = '01-17-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case77: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 77 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '77' AND drug_concept_id = '0' AND drug_exposure_start_date = '07-08-2006') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case79: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 79 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '79' AND drug_concept_id = '45775771' AND drug_exposure_start_date = '09-18-2014') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case81: Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)
INSERT INTO cdm_testing_ccae.test_results SELECT 81 AS id, 'Tofacitinib mapps to 11-digit DRUG_SOURCE_CONCEPT_ID instead of 9-digit (HIX-1534)' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '81' AND drug_source_concept_id = '45332969') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case83: HRA Drug still has a DRUG_EXPOSURE_END_DATE (HIX-1433). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 83 AS id, 'HRA Drug still has a DRUG_EXPOSURE_END_DATE (HIX-1433). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '83' AND drug_concept_id = '4214838' AND drug_exposure_end_date = '2012-05-25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case85: Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 85 AS id, 'Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '85' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case87: Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 87 AS id, 'Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '87' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case89: Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 89 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '89' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 89 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '89') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case91: Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 91 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '91' AND drug_concept_id = '1134439' AND drug_era_start_date = '09-21-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 91 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '91' AND drug_concept_id = '1134439' AND drug_era_start_date = '12-08-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case93: Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 93 AS id, 'Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '93' AND drug_concept_id = '956874' AND drug_era_start_date = '12-08-2010' AND drug_era_end_date = '12-22-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case95: No drug era created from procedure drugs since they are not related to ingredients. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 95 AS id, 'No drug era created from procedure drugs since they are not related to ingredients. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '95') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case97: Drug with two ingredients should have two drug eras. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 97 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '97' AND drug_concept_id = '1134439' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 97 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '97' AND drug_concept_id = '1112807' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case99: Two drugs with same ingredient within 30 days, one occurs outside of observation_period. Drug era should only include drug inside observation_period. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 99 AS id, 'Two drugs with same ingredient within 30 days, one occurs outside of observation_period. Drug era should only include drug inside observation_period. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_era WHERE person_id = '99' AND drug_concept_id = '1134439' AND drug_era_start_date = '01-08-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case101: Location record generated for egeoloc 11. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 101 AS id, 'Location record generated for egeoloc 11. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.location WHERE state = 'NJ' AND location_source_value = '11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case102: No location record generated for egeoloc 89. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 102 AS id, 'No location record generated for egeoloc 89. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.location WHERE location_source_value = '89') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case103: Only one location record generated for 38. Id is PERSON_ID
INSERT INTO cdm_testing_ccae.test_results SELECT 103 AS id, 'Only one location record generated for 38. Id is PERSON_ID' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.location WHERE state = 'VA' AND location_source_value = '38') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case104: LOINC code does not have a dash in the second to last character, record is dropped. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 104 AS id, 'LOINC code does not have a dash in the second to last character, record is dropped. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '104') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case106: Svcdate is outside of observation period, record is dropped. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 106 AS id, 'Svcdate is outside of observation period, record is dropped. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '106') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case108: Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 108 AS id, 'Patient has abnormal=L; value as concept_id = 4267416. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '108' AND value_as_concept_id = '4267416') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case110: Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 110 AS id, 'Patient has result ne 0 and > neg 99999, result listed in value as number field. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '110' AND value_as_number = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case112: Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 112 AS id, 'Patient lowercase units, maps to unit_concept_id 8840 (HIX-1183). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '112' AND value_as_number = '100' AND unit_concept_id = '8840') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case114: If you do not get a map from UCUM for UNIT_CONCEPT_ID then try JNJ_UNITS (HIX-1419). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 114 AS id, 'If you do not get a map from UCUM for UNIT_CONCEPT_ID then try JNJ_UNITS (HIX-1419). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '114' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case116: for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 116 AS id, 'for LOINCs 3142-7, 29463-7, 3141-9 sometimes padded with 0000, strip padding (HIX-1418). Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '116' AND value_as_number = '150' AND unit_concept_id = '8739') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case118: Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 118 AS id, 'Patient has 2 in CGTPKAMT column, value_as_number=1 pack per day or more. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '118' AND measurement_date = '2012-03-14' AND value_as_number = '2' AND measurement_source_value = 'CGTPKAMT' AND value_source_value = '1 pack per day or more') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case120: Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 120 AS id, 'Patient has weight 201, value_as_string = null, value_as_number=201. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '120' AND measurement_date = '2012-07-16' AND value_as_number = '201' AND measurement_source_value = 'WEIGHT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case122: BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 122 AS id, 'BMI is only question answered bmi is only record created in observation . Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '122' AND measurement_date = '2012-09-22' AND value_as_number = '28.6' AND measurement_source_value = 'BMI') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case124: Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 124 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation_period WHERE person_id = '124' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case125: Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 125 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation_period WHERE person_id = '125' AND observation_period_start_date = '2012-05-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case126: Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 126 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation_period WHERE person_id = '126' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-06-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 126 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation_period WHERE person_id = '126' AND observation_period_start_date = '2012-08-02' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case127: Store Discharge Status. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 127 AS id, 'Store Discharge Status. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '127' AND observation_concept_id = '4202605' AND observation_source_value = '51') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case129: SVCDATE is outside of observation_period, measurement record created . Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 129 AS id, 'SVCDATE is outside of observation_period, measurement record created . Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '129' AND measurement_date = '2013-10-13' AND value_as_number = '20.0' AND measurement_source_value = 'BMI') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case131: Patient answered 3 for question EXERWEEK, value_as_number=3. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 131 AS id, 'Patient answered 3 for question EXERWEEK, value_as_number=3. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '131' AND observation_date = '2012-05-25' AND value_as_number = '3' AND observation_source_value = 'EXERWEEK') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case133: Patient answered 1 for question FLU_SHOT, drug_exposure record created (HIX-1299). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 133 AS id, 'Patient answered 1 for question FLU_SHOT, drug_exposure record created (HIX-1299). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '133' AND drug_concept_id = '4214838') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case135: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 135 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '135') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case136: Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 136 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '136' AND payer_plan_period_start_date = '2013-01-01' AND payer_plan_period_end_date = '2013-01-31' AND payer_source_value = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 136 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '136' AND payer_plan_period_start_date = '2013-05-01' AND payer_plan_period_end_date = '2013-05-31' AND payer_source_value = 'N Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case137: Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 137 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '137' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-06' AND payer_source_value = 'C Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 137 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '137' AND payer_plan_period_start_date = '2012-04-07' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'C Commercial POS') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case138: Person has duplicate records, only one is brought into the cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 138 AS id, 'Person has duplicate records, only one is brought into the cdm. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.payer_plan_period WHERE person_id = '138' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'C Commercial PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case139: Person with two genders is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 139 AS id, 'Person with two genders is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '139') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case140: Person with two birth years >2 yrs apart is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 140 AS id, 'Person with two birth years >2 yrs apart is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '140') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case141: Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 141 AS id, 'Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '141' AND year_of_birth = '1971') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case142: Person born before 1900 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 142 AS id, 'Person born before 1900 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '142') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case143: Person born in 2099 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 143 AS id, 'Person born in 2099 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '143') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case144: Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 144 AS id, 'Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '144') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case145: Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 145 AS id, 'Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '145' AND year_of_birth = '2013') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case146: Person with two enrollment_detail records has one person record. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 146 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '146' AND year_of_birth = '1980') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case147: Person with sex=3 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 147 AS id, 'Person with sex=3 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '147') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case148: Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 148 AS id, 'Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '148' AND gender_concept_id = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case149: Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 149 AS id, 'Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '149' AND year_of_birth = '2012' AND month_of_birth = '4' AND day_of_birth = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case150: Person with Rx benefits is kept. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 150 AS id, 'Person with Rx benefits is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '150') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case151: Person without Rx benefits is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 151 AS id, 'Person without Rx benefits is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '151') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case152: Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 152 AS id, 'Person with last enrollment_detail record that has egeoloc=11 gets associated to NJ. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.person WHERE person_id = '152') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case153: Patient has two PPROC values, PPROC from inpatient_admissions is used. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 153 AS id, 'Patient has two PPROC values, PPROC from inpatient_admissions is used. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '153' AND procedure_concept_id = '40757126' AND procedure_date = '2012-06-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case155: Patient has two different providers for the same procedure, the provider on the first line (ascending) is chosen. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 155 AS id, 'Patient has two different providers for the same procedure, the provider on the first line (ascending) is chosen. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '155' AND procedure_concept_id = '2109659' AND procedure_date = '2012-10-20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case157: Patient has HCPCS procedure code with value in PROCMOD, only HCPCS comes across in record since PROCMOD associated with CPT4 only. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 157 AS id, 'Patient has HCPCS procedure code with value in PROCMOD, only HCPCS comes across in record since PROCMOD associated with CPT4 only. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '157' AND procedure_concept_id = '2616464' AND procedure_date = '2012-05-12' AND modifier_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case159: Patient has two records for the same procedure, procedure in outpatient_services prioritized. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 159 AS id, 'Patient has two records for the same procedure, procedure in outpatient_services prioritized. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '159' AND procedure_concept_id = '2109995' AND procedure_date = '2012-02-15' AND procedure_type_concept_id = '38000267') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case161: Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 38000273. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 161 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 38000273. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '161' AND procedure_concept_id = '2313827' AND procedure_type_concept_id = '38000273') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case163: Patient has procedure with domain = device, device record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 163 AS id, 'Patient has procedure with domain = device, device record created. Id is PERSON_ID.' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.device_exposure WHERE person_id = '163' AND device_concept_id = '2616599' AND device_exposure_start_date = '2012-04-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case165: Patient has procedure with domain = drug, drug record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 165 AS id, 'Patient has procedure with domain = drug, drug record created. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.drug_exposure WHERE person_id = '165' AND drug_concept_id = '44816520' AND drug_exposure_start_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case167: Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 167 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.measurement WHERE person_id = '167' AND measurement_concept_id = '2212375' AND measurement_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case169: Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 169 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.observation WHERE person_id = '169' AND observation_concept_id = '2721503' AND observation_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case171: Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 171 AS id, 'Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.procedure_occurrence WHERE person_id = '171' AND procedure_concept_id = '2789746' AND procedure_date = '2016-06-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case173: Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_ccae.test_results SELECT 173 AS id, 'Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.provider WHERE specialty_concept_id = '38004510' AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case175: Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_ccae.test_results SELECT 175 AS id, 'Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.provider WHERE specialty_concept_id = '38004484' AND specialty_source_value = '285') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case177: provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_ccae.test_results SELECT 177 AS id, 'provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.provider WHERE specialty_concept_id = '38004497' AND specialty_source_value = '540') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case179: provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_ccae.test_results SELECT 179 AS id, 'provider in lab table with stdprov =22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.provider WHERE specialty_concept_id = '38004498' AND specialty_source_value = '22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case181: Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_ccae.test_results SELECT 181 AS id, 'Even when PROVID IS NULL create a PROVIDER (HIX-1404). Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.provider WHERE provider_source_value = '' AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case183: Patient with visit that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 183 AS id, 'Patient with visit that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '183' AND visit_start_date = '2012-01-01' AND visit_end_date = '2012-01-06') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case185: svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 185 AS id, 'svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '185' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case187: Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 187 AS id, 'Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '187' AND visit_start_date = '2012-12-30' AND visit_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case189: service in inpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 189 AS id, 'service in inpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '189' AND visit_concept_id = '9203' AND visit_start_date = '2012-04-12' AND visit_end_date = '2012-04-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case191: service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 191 AS id, 'service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '191' AND visit_concept_id = '9203' AND visit_start_date = '2012-05-01' AND visit_end_date = '2012-05-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case193: service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 193 AS id, 'service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '193' AND visit_concept_id = '9201' AND visit_start_date = '2012-10-17' AND visit_end_date = '2012-10-20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case195: Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)
INSERT INTO cdm_testing_ccae.test_results SELECT 195 AS id, 'Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID. (HIX-1521)' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '195' AND visit_start_date = '2012-10-01' AND preceding_visit_occurrence_id = (SELECT visit_occurrence_id FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '195' AND visit_start_date = '2012-08-08')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case197: patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 197 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '197' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 197 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '197' AND visit_start_date = '2012-10-01' AND visit_end_date = '2012-10-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case199: Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 199 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '199' AND visit_concept_id = '9203' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_ccae.test_results SELECT 199 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '199' AND visit_concept_id = '9201' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case201: Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 201 AS id, 'Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '201') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case203: Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 203 AS id, 'Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '203' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21' AND discharge_to_concept_id = '8536') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case205: Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 205 AS id, 'Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '205') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- Test Case207: Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.
INSERT INTO cdm_testing_ccae.test_results SELECT 207 AS id, 'Patient has two records in the same visit with different provid and provstd. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_ccae.visit_occurrence WHERE person_id = '207' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;