IF OBJECT_ID('cdm_testing_MDCD.test_results', 'U') IS NOT NULL DROP TABLE cdm_testing_MDCD.test_results;
CREATE TABLE cdm_testing_MDCD.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 1: Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, the inpatient_admissions PDX is used. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 1 AS id, 'Patient has two different primary diagnoses between inpatient_services and inpatient_admissions, the inpatient_admissions PDX is used. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '1' AND condition_concept_id = '198337' AND condition_type_concept_id = '38000199') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3: Patient has the same diagnosis code in outpatient_services and facility_header but in different positions, outpatient_services dx is prioritized. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 3 AS id, 'Patient has the same diagnosis code in outpatient_services and facility_header but in different positions, outpatient_services dx is prioritized. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '3' AND condition_concept_id = '433706' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 5: Patient has diagnosis in dx4 field in inpatient_services, condition_type_concept_id = 38000187. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 5 AS id, 'Patient has diagnosis in dx4 field in inpatient_services, condition_type_concept_id = 38000187. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '5' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 7: Patient has diagnosis in dx9 field in facility_header, condition_type_concept_id = 38000208. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 7 AS id, 'Patient has diagnosis in dx9 field in facility_header, condition_type_concept_id = 38000208. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '7' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000208') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 9: Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '9' AND visit_concept_id = '9203') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '195587' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 9 AS id, 'Patient has revcode 0450 and diagnosis codes in the pdx and dx1 fields, ER record created and conditions have condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '9' AND condition_concept_id = '24970' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 11: Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 11 AS id, 'Patient has diagnosis in a dx field that has domain=procedure, condition record moved to procedure_occurrence. Id is PERSON_ID' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '11' AND procedure_concept_id = '4064909') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13: Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 13 AS id, 'Patient has diagnosis in a dx field that has domain=observation, condition record moved to observation. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation WHERE person_id = '13' AND observation_concept_id = '4117957') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15: Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 15 AS id, 'Patient has diagnosis in a dx field that has domain=measurement, condition record moved to measurement. Id is PERSON_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.measurement WHERE person_id = '15' AND measurement_concept_id = '4034850') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17: Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 17 AS id, 'Patient has icd10 diagnosis in a dx field with dxver=0, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '17' AND condition_concept_id = '438021') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19: patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation WHERE person_id = '19' AND observation_concept_id = '437476') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 19 AS id, 'patient has icd10cm diagnosis in a dx field that overlaps with an icd10 diagnosis, condition record created with icd10cm mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '19' AND condition_concept_id = '4053838') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21: Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 21 AS id, 'Patient has icd10 diagnosis after 10/1/2015 in a dx field with dxver=null, condition record created with icd10 mapped to snomed. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '21' AND condition_concept_id = '438021') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23: Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 23 AS id, 'Patient has icd9 diagnosis before 10/1/2015 in a dx field with dxver=null, used ICD9. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '23' AND condition_concept_id = '4053838' AND condition_source_concept_id = '44821630') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 25: Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-07-01' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 25 AS id, 'Patient has two IP records in inpatient_services with svcdate = condition_start_date (HIX-1274). Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '25' AND condition_concept_id = '195587' AND condition_start_date = '2012-08-02' AND condition_type_concept_id = '38000187') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27: Patient has diagnosis in dx1 in ltc, condition_type_concept_id = 38000215. Id is PERSON_ID
INSERT INTO cdm_testing_MDCD.test_results SELECT 27 AS id, 'Patient has diagnosis in dx1 in ltc, condition_type_concept_id = 38000215. Id is PERSON_ID' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '27' AND condition_concept_id = '4053838' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29: Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 29 AS id, 'Patient condition_concept_id of 0, no condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_era WHERE person_id = '29') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31: Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 31 AS id, 'Two records with same condition_concept_id are less than 30 days apart, one condition_era record created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_era WHERE person_id = '31' AND condition_era_start_date = '2012-07-01' AND condition_era_end_date = '2012-07-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33: Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 33 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_era WHERE person_id = '33' AND condition_era_start_date = '2012-07-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 33 AS id, 'Two records with same condition_concept_id are more than 30 days apart, two condition_era records created. Id is PERSON_ID.' AS description, 'Expect condition_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_era WHERE person_id = '33' AND condition_era_start_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35: Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 35 AS id, 'Patient has values in ingcost, dispfee and AWP (HIX-1319). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Drug' AND total_cost = '20' AND paid_patient_copay = '20' AND paid_ingredient_cost = '50' AND paid_dispensing_fee = '25') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37: Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 37 AS id, 'Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '37' AND procedure_concept_id = '40757105' AND procedure_date = '2012-06-11') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 37 AS id, 'Patient has cost values, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '160' AND paid_patient_copay = '40' AND paid_patient_deductible = '120') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39: Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 39 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.measurement WHERE person_id = '39' AND measurement_concept_id = '2212375' AND measurement_date = '2012-05-07') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 39 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Measurement' AND total_paid = '157' AND paid_by_payer = '120' AND paid_patient_copay = '37') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41: Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 41 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation WHERE person_id = '41' AND observation_concept_id = '2721503' AND observation_date = '2012-10-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 41 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Observation' AND paid_by_payer = '75' AND paid_patient_coinsurance = '100' AND paid_by_primary = '52') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43: Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 43 AS id, 'Patient has cost values and revenue code, cost is correctly associated with cost_domain_id = 10. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '100' AND paid_patient_copay = '80' AND paid_patient_deductible = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45: Testing DRG Populates (HIX-1431). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 45 AS id, 'Testing DRG Populates (HIX-1431). Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Procedure' AND paid_by_patient = '100' AND paid_patient_copay = '80' AND paid_patient_deductible = '20' AND drg_concept_id = '38000893') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47: Patient has record with costs in ltc, cost record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 47 AS id, 'Patient has record with costs in ltc, cost record created. Id is PERSON_ID.' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.condition_occurrence WHERE person_id = '47' AND condition_concept_id = '4053838' AND condition_type_concept_id = '38000215') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 47 AS id, 'Patient has record with costs in ltc, cost record created. Id is PERSON_ID.' AS description, 'Expect cost' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.cost WHERE cost_domain_id = 'Procedure' AND paid_by_payer = '90' AND paid_by_patient = '150' AND paid_patient_copay = '62' AND paid_patient_coinsurance = '88' AND paid_by_primary = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49: Date of death visit end date. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 49 AS id, 'Date of death visit end date. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '49' AND death_date = '2013-01-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51: ICD10 Death and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 51 AS id, 'ICD10 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '51' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53: ICD9 Death and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 53 AS id, 'ICD9 Death and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '53' AND death_type_concept_id = '38003567') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55: Discharge Status and Death Type Correct. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 55 AS id, 'Discharge Status and Death Type Correct. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '55' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57: Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 57 AS id, 'Death by ICD9 and Death by Discharge, Keep the Discharge. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '57' AND death_type_concept_id = '38003566') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59: Death and then contined Activity Cancels Death. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 59 AS id, 'Death and then contined Activity Cancels Death. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '59') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61: Patient has icd9 death cord in ltc, death record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 61 AS id, 'Patient has icd9 death cord in ltc, death record created. Id is PERSON_ID.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.death WHERE person_id = '61') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63: Duplicate drug records become one record in the CDM. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 63 AS id, 'Duplicate drug records become one record in the CDM. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '63' AND drug_concept_id = '40161912' AND drug_exposure_start_date = '02-01-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65: Negative daysupp should be 0 in cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 65 AS id, 'Negative daysupp should be 0 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '65' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '06-12-2012' AND days_supply = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67: Daysupp >365 should be 365 in cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 67 AS id, 'Daysupp >365 should be 365 in cdm. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '67' AND drug_concept_id = '1545998' AND drug_exposure_start_date = '08-07-2012' AND days_supply = '365') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69: CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 69 AS id, 'CPT4 drug code in inpatient record moves to drug_exposure. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '69' AND drug_concept_id = '2213404' AND drug_exposure_start_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71: Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 71 AS id, 'Days supply is NULL but DRUG_EXPOSURE_END_DATE is set to DRUG_EXPOSURE_START_DATE (HIX-1430). Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '71' AND drug_concept_id = '2213404' AND drug_exposure_start_date = '2012-08-09' AND drug_exposure_end_date = '2012-08-09') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73: Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 73 AS id, 'Patient has 11 digit NDC that doesn''t map, should use first 9 digits instead. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '73' AND drug_concept_id = '46275250' AND drug_exposure_start_date = '01-17-2012') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 75 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID=0 because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '75' AND drug_concept_id = '0' AND drug_exposure_start_date = '07-08-2006') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77: Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 77 AS id, 'Patient has 9 digit NDC that doesn''t map, should use first 9 digits instead, should map to correct DRUG_CONCEPT_ID because of the date filter. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '77' AND drug_concept_id = '45775771' AND drug_exposure_start_date = '09-18-2014') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79: Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 79 AS id, 'Two drugs with same ingredient within 30 days, should be one drug era. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '79' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81: Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 81 AS id, 'Two drugs with same ingredient within 30 days, but 10 gap days. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '81' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83: Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 83 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '83' AND drug_concept_id = '1134439' AND drug_era_start_date = '02-04-2012' AND gap_days = '10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 83 AS id, 'Three drugs with same ingredient within 30 days, but 10 gap days total (5 between each). Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '83') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 85 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '85' AND drug_concept_id = '1134439' AND drug_era_start_date = '09-21-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 85 AS id, 'Two drugs with same ingredient > 30 days apart, should be two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '85' AND drug_concept_id = '1134439' AND drug_era_start_date = '12-08-2012' AND gap_days = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87: Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 87 AS id, 'Drug_era_end_date should be drug start date + days supply. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '87' AND drug_concept_id = '956874' AND drug_era_start_date = '12-08-2010' AND drug_era_end_date = '12-22-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 89: No drug era created from procedure drugs since they are not related to ingredients. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 89 AS id, 'No drug era created from procedure drugs since they are not related to ingredients. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '89') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 91: Drug with two ingredients should have two drug eras. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 91 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '91' AND drug_concept_id = '1134439' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 91 AS id, 'Drug with two ingredients should have two drug eras. Id is PERSON_ID.' AS description, 'Expect drug_era' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_era WHERE person_id = '91' AND drug_concept_id = '1112807' AND drug_era_start_date = '05-01-2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 93: Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 93 AS id, 'Subsumed enrollment test where two enrollment durations with the second subsumed by the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation_period WHERE person_id = '93' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 94: Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 94 AS id, 'Combine enrollment test where two enrollment durations with the second within 30 days of the first results in a single observation. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation_period WHERE person_id = '94' AND observation_period_start_date = '2012-05-01' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 95: Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 95 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation_period WHERE person_id = '95' AND observation_period_start_date = '2012-01-01' AND observation_period_end_date = '2012-06-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 95 AS id, 'Gap enrollment test where two enrollment durations are 33 days apart results in two observations. Id is PERSON_ID.' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation_period WHERE person_id = '95' AND observation_period_start_date = '2012-08-02' AND observation_period_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 96: Store Discharge Status. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 96 AS id, 'Store Discharge Status. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation WHERE person_id = '96' AND observation_concept_id = '4202605' AND observation_source_value = '51') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 98: Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 98 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '98' AND payer_plan_period_start_date = '2013-01-01' AND payer_plan_period_end_date = '2013-01-31' AND payer_source_value = 'D C Medicaid PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 98 AS id, 'Person has a gap of >32 days between enrollment periods with the same payer_source_value; person has two records. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '98' AND payer_plan_period_start_date = '2013-05-01' AND payer_plan_period_end_date = '2013-05-31' AND payer_source_value = 'D C Medicaid PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 99: Person does not have prescription benefits and is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 99 AS id, 'Person does not have prescription benefits and is excluded. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '99') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 100: Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 100 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '100' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-06' AND payer_source_value = 'D C Medicaid PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 100 AS id, 'Person switches plans in the middle of an enrollment period; person has two records with the first truncated. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '100' AND payer_plan_period_start_date = '2012-04-07' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'D C Medicaid POS') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 101: Person has duplicate records, only one is brought into the cdm. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 101 AS id, 'Person has duplicate records, only one is brought into the cdm. Id is PERSON_ID.' AS description, 'Expect payer_plan_period' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.payer_plan_period WHERE person_id = '101' AND payer_plan_period_start_date = '2012-04-01' AND payer_plan_period_end_date = '2012-04-30' AND payer_source_value = 'D C Medicaid PPO') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 102: Person with two genders is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 102 AS id, 'Person with two genders is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '102') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 103: Person with two birth years >2 yrs apart is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 103 AS id, 'Person with two birth years >2 yrs apart is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '103') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 104: Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 104 AS id, 'Person with two birth years <2 yrs apart is kept with last birth year selected. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '104' AND year_of_birth = '1971') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 105: Person born before 1900 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 105 AS id, 'Person born before 1900 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '105') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 106: Person born in 2099 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 106 AS id, 'Person born in 2099 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '106') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 107: Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 107 AS id, 'Person born in 2014 but enrolled in 2012 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '107') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 108: Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 108 AS id, 'Person born in 2013 but enrolled in 2012 is kept, latest birth year taken. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '108' AND year_of_birth = '2013') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 109: Person with two enrollment_detail records has one person record. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 109 AS id, 'Person with two enrollment_detail records has one person record. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '109' AND year_of_birth = '1980') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 110: Person with sex=3 is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 110 AS id, 'Person with sex=3 is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '110') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 111: Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 111 AS id, 'Person has record with sex=3 but last record has sex=1, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '111' AND gender_concept_id = '8507') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 112: Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 112 AS id, 'Person born the same year as enrolled, use first enrollment month to impute month of birth and day of birth. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '112' AND year_of_birth = '2012' AND month_of_birth = '4' AND day_of_birth = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 113: Person with DRUGCOVG=0 and MEDICARE=0, person is excluded. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 113 AS id, 'Person with DRUGCOVG=0 and MEDICARE=0, person is excluded. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '113') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 114: Person with DRUGCOVG=1 and MEDICARE=0, person is kept. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 114 AS id, 'Person with DRUGCOVG=1 and MEDICARE=0, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '114') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 115: Person with DRUGCOVG=0 and MEDICARE=1, person is kept. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 115 AS id, 'Person with DRUGCOVG=0 and MEDICARE=1, person is kept. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '115') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 116: Person with stdrace=1. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 116 AS id, 'Person with stdrace=1. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '116' AND race_concept_id = '8527' AND ethnicity_concept_id = '38003564') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 117: Person with stdrace=4. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 117 AS id, 'Person with stdrace=4. Id is PERSON_ID.' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.person WHERE person_id = '117' AND race_concept_id = '0' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 118: Patient has two PPROC values, PPROC from inpatient_admissions is used. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 118 AS id, 'Patient has two PPROC values, PPROC from inpatient_admissions is used. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '118' AND procedure_concept_id = '40757126' AND procedure_date = '2012-06-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 120: Patient has two different providers for the same procedure, the provider on the first line (ascending) is chosen. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 120 AS id, 'Patient has two different providers for the same procedure, the provider on the first line (ascending) is chosen. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '120' AND procedure_concept_id = '2109659' AND procedure_date = '2012-10-20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 122: Patient has procedure in proc1 field in long_term_care table. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 122 AS id, 'Patient has procedure in proc1 field in long_term_care table. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '122' AND procedure_concept_id = '2313736' AND procedure_date = '2012-09-15') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 124: Patient has two records for the same procedure, procedure in outpatient_services prioritized. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 124 AS id, 'Patient has two records for the same procedure, procedure in outpatient_services prioritized. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '124' AND procedure_concept_id = '2109995' AND procedure_date = '2012-02-15' AND procedure_type_concept_id = '38000267') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 126: Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 38000273. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 126 AS id, 'Patient has procedure in proc5 position in facility header, procedure_type_concept_id = 38000273. Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '126' AND procedure_concept_id = '2313827' AND procedure_type_concept_id = '38000273') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 128: Patient has procedure with domain = device, device record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 128 AS id, 'Patient has procedure with domain = device, device record created. Id is PERSON_ID.' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.device_exposure WHERE person_id = '128' AND device_concept_id = '2616599' AND device_exposure_start_date = '2012-04-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 130: Patient has procedure with domain = drug, drug record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 130 AS id, 'Patient has procedure with domain = drug, drug record created. Id is PERSON_ID.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.drug_exposure WHERE person_id = '130' AND drug_concept_id = '44816520' AND drug_exposure_start_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 132: Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 132 AS id, 'Patient has procedure with domain = measurement, measurement record created. Id is PERSON_ID.' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.measurement WHERE person_id = '132' AND measurement_concept_id = '2212375' AND measurement_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 134: Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 134 AS id, 'Patient has procedure with domain = observation, observation record created. Id is PERSON_ID.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.observation WHERE person_id = '134' AND observation_concept_id = '2721503' AND observation_date = '2012-05-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 136: Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 136 AS id, 'Patient has an ICD10PCS value in inpatient_admissions field pdx, pdx is correctly mapped and a procedure_occurrence record created (HIX-1255). Id is PERSON_ID.' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.procedure_occurrence WHERE person_id = '136' AND procedure_concept_id = '2789746' AND procedure_date = '2016-06-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 138: Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_MDCD.test_results SELECT 138 AS id, 'Provider in facility header table with stdprov=220, specialty = emergency medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.provider WHERE specialty_concept_id = '38004510' AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 140: Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_MDCD.test_results SELECT 140 AS id, 'Provider in outpatient_services table with stdprov=285, specialty = infectious disease. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.provider WHERE specialty_concept_id = '38004484' AND specialty_source_value = '285') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 142: provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_MDCD.test_results SELECT 142 AS id, 'provider in inpatient_services table with stdprov=540, specialty = cardiac surgery. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.provider WHERE specialty_concept_id = '38004497' AND specialty_source_value = '540') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 144: provider in long_term_care table with stdprov=22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE
INSERT INTO cdm_testing_MDCD.test_results SELECT 144 AS id, 'provider in long_term_care table with stdprov=22, specialty = addiction medicine. Id is PROVIDER_SOURCE_VALUE' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.provider WHERE specialty_concept_id = '38004498' AND specialty_source_value = '22') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 146: Even when PROVID IS NULL create a PROVIDER (HIX-1404)
INSERT INTO cdm_testing_MDCD.test_results SELECT 146 AS id, 'Even when PROVID IS NULL create a PROVIDER (HIX-1404)' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.provider WHERE provider_source_value = '' AND specialty_source_value = '220') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 148: Patient with visit that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 148 AS id, 'Patient with visit that starts before the observation period, start date trimmed to beginning of observation period. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '148' AND visit_start_date = '2012-01-01' AND visit_end_date = '2012-01-06') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 150: svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 150 AS id, 'svcdate>tsvcdate, visit_end_date is svcdate. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '150' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 152: Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 152 AS id, 'Service falls during observation period but ends after the period ends, visit_end_date is the observation_period_end_date. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '152' AND visit_start_date = '2012-12-30' AND visit_end_date = '2012-12-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 154: service in inpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 154 AS id, 'service in inpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '154' AND visit_concept_id = '9203' AND visit_start_date = '2012-04-12' AND visit_end_date = '2012-04-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 156: service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 156 AS id, 'service in outpatient_services with revcode of 0450, visit classified as ER. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '156' AND visit_concept_id = '9203' AND visit_start_date = '2012-05-01' AND visit_end_date = '2012-05-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 158: service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 158 AS id, 'service in outpatient_services with revcode of 0100, visit classified as IP. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '158' AND visit_concept_id = '9201' AND visit_start_date = '2012-10-17' AND visit_end_date = '2012-10-20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 160: Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 160 AS id, 'Two visits created, expect a visit with a PRECEDING_VISIT_OCCURRENCE_ID. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '160' AND visit_start_date = '2012-10-01' AND preceding_visit_occurrence_id = (SELECT visit_occurrence_id FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '160' AND visit_start_date = '2012-08-08')) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 162: patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 162 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '162' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 162 AS id, 'patient has two lines in the inpatient_services table where the end_date of one line and the start_date of the next >1, two visits created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '162' AND visit_start_date = '2012-10-01' AND visit_end_date = '2012-10-05') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 164: Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 164 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '164' AND visit_concept_id = '9203' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-03') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO cdm_testing_MDCD.test_results SELECT 164 AS id, 'Patient has an ER record that starts and ends on the first day of the IP visit, separate ER visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '164' AND visit_concept_id = '9201' AND visit_start_date = '2012-09-03' AND visit_end_date = '2012-09-10') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 166: Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 166 AS id, 'Patient has two lines in the inpatient_services table where the difference between the end_date of one line and the start_date of the next is <= 1, one visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '166') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 168: Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 168 AS id, 'Setting Discharge_to_Concept_id for IP Record (HIX-1429). Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '168' AND visit_start_date = '2012-03-21' AND visit_end_date = '2012-03-21' AND discharge_to_concept_id = '8536') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 170: Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 170 AS id, 'Patient has record in outpatient_services table but no rx benefits, visit dropped. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE visit_occurrence_id = '170') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 172: Patient has two records in the same visit with different prov_id and provstd. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 172 AS id, 'Patient has two records in the same visit with different prov_id and provstd. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '172' AND visit_start_date = '2012-08-08' AND visit_end_date = '2012-08-12') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 176: Patient has two LTC claims where the end_date of the first is within one day of the start_date of the second, one visit created. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 176 AS id, 'Patient has two LTC claims where the end_date of the first is within one day of the start_date of the second, one visit created. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '176' AND visit_start_date = '2012-06-18' AND visit_end_date = '2012-07-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 178: Patient has LTC claim where the end_date = the start_date. Id is PERSON_ID.
INSERT INTO cdm_testing_MDCD.test_results SELECT 178 AS id, 'Patient has LTC claim where the end_date = the start_date. Id is PERSON_ID.' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM cdm_testing_MDCD.visit_occurrence WHERE person_id = '178' AND visit_start_date = '2012-08-01' AND visit_end_date = '2012-08-31') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;