/*CCAE Sprint 6 Test Cases Table 11 Deat*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their deaths will not come through*/

/*1101*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1101,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1102*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1102,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1103*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1103,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1104*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1104,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)

/*Insert values into inpatient_services, facility_header and inpatient_admissions to create procedure_cost records (procedure_occurrence records will also be created by default)*/

/*1101*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 40, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1101, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-06-01' as Date), NULL, Cast('2012-06-03' as Date), NULL, NULL, 2012, NULL, NULL)

/*1102*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1102, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-08-04' as Date), NULL, Cast('2012-08-06' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1102, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-08-04' as Date), NULL, Cast('2012-08-07' as Date), NULL, NULL, 2012, NULL, NULL)

/*1103*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1103, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-09-04' as Date), NULL, Cast('2012-09-10' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1103, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, N'2500', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-11-27' as Date), NULL, Cast('2012-11-28' as Date), NULL, NULL, 2012, NULL, NULL)

/*1104*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11041, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 23, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1104, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-12-02' as Date), NULL, Cast('2012-12-05' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 11041, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1104, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, N'7981', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-12-08' as Date), NULL, Cast('2012-12-09' as Date), NULL, NULL, 2012, NULL, NULL)
