SELECT DISTINCT SOURCE_CODE, TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP
WHERE SOURCE_VOCABULARY_ID = 6
				AND TARGET_VOCABULARY_ID = 6
				AND PRIMARY_MAP = 'Y'
				AND (INVALID_REASON IS NULL or INVALID_REASON = '')
				AND GETDATE() BETWEEN VALID_START_DATE AND VALID_END_DATE
				AND SUBSTRING(RIGHT(SOURCE_CODE, 2),1,1) = '-' /*make sure the 2nd to last character is a dash*/
