/*CCAE Sprint 6 Test Cases Table 12 Drug Exposure*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their drugs will not come through*/

/*1201*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1201,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1202*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1202,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1203*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1203,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1204*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1204,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1205*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1205,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1206*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2006-12-31' as Date),	Cast (N'2006-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1206,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1207*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2014-12-31' as Date),	Cast (N'2014-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1207,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)

/*Create Drug Claims records*/
/*1201 - Duplicate records become one record in CDM*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1201, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        13533063512, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('02-01-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1201, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        13533063512, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('02-01-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

/*1202 - Daysupp negative, should come across as 0 in CDM*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, -250, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1202, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        36987257801, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('06-12-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

/*1203 - Daysupp >365, should come across as 365 in CDM*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 432, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1203, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        36987257801, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('08-07-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

/*1204 - CPT4 code on inpatient record codes for drug, should be in drug instead of procedure_occurrence in CDM*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 12041, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1204, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-09-09' as Date), NULL, Cast('2012-09-12' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES       (NULL, NULL, NULL, NULL, 12041, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1204, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 90376, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL)

/*1205 - Patient has 11 digit NDC that doesn't map, should use first 9 digits instead*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1205, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        13533063670, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('01-17-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

/*1206 - Patient has 11 digit NDC that doesn't map, should use first 9 digits instead, should map to DRUG_CONCEPT_ID = 0 due to the new date filter on 11/24/2015*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1206, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        right('0000'+'00006000543',11), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('07-08-2006' as date), NULL, NULL, NULL, NULL, 2006, NULL)

/*1207 - Patient has 11 digit NDC that doesn't map, should use first 9 digits instead, should map to the correct DRUG_CONCEPT_ID due to the new date filter on 11/24/2015*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1207, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        right('0000'+'00006032582',11), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('09-18-2014' as date), NULL, NULL, NULL, NULL, 2014, NULL)
