/*CCAE Sprint 6 Test Cases Table 19 Measurement*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their labs will not come through*/

/*1901*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1901,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1902*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1902,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1903*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1903,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1904*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1904,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)

/*1901 - LOINCCD does not have a '-' in the second to last character; record is dropped*/
INSERT [dbo].[LAB](ENROLID, SEQNUM, ABNORMAL, AGEGRP, EECLASS, EESTATU, EIDFLAG, EMPREL, ENRFLAG, HLTHPLAN, INDSTRY, MHSACOVG, PHYFLAG, PROCTYP, 
                         REGION, RX, SEX, EGEOLOC, MDC, VERSION, RESLTCAT, DX1, PROC1, PDDATE, SVCDATE, MSA, ORDERID, PROVID, REFHIGH, REFLOW, RESULT, TESTCNT, 
                         DOBYR, PLANKEY, STDPROV, WGTKEY, YEAR, AGE, DATATYP, PLANTYP, STDPLAC, LOINCCD, RESUNIT, EFAMID)
VALUES        (1901, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('03-07-2012' as Date), NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'99999', NULL, NULL)

/*1902 - SVCDATE is outside of observation_period; record is dropped*/
INSERT [dbo].[LAB](ENROLID, SEQNUM, ABNORMAL, AGEGRP, EECLASS, EESTATU, EIDFLAG, EMPREL, ENRFLAG, HLTHPLAN, INDSTRY, MHSACOVG, PHYFLAG, PROCTYP, 
                         REGION, RX, SEX, EGEOLOC, MDC, VERSION, RESLTCAT, DX1, PROC1, PDDATE, SVCDATE, MSA, ORDERID, PROVID, REFHIGH, REFLOW, RESULT, TESTCNT, 
                         DOBYR, PLANKEY, STDPROV, WGTKEY, YEAR, AGE, DATATYP, PLANTYP, STDPLAC, LOINCCD, RESUNIT, EFAMID)
VALUES        (1902, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('07-09-2013' as Date), NULL, NULL, NULL, NULL, NULL, 32, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'56773-5', NULL, NULL)

/*1903 - Patient has abnormal='L'; value_as_concept_id = 4132135*/
INSERT [dbo].[LAB](ENROLID, SEQNUM, ABNORMAL, AGEGRP, EECLASS, EESTATU, EIDFLAG, EMPREL, ENRFLAG, HLTHPLAN, INDSTRY, MHSACOVG, PHYFLAG, PROCTYP, 
                         REGION, RX, SEX, EGEOLOC, MDC, VERSION, RESLTCAT, DX1, PROC1, PDDATE, SVCDATE, MSA, ORDERID, PROVID, REFHIGH, REFLOW, RESULT, TESTCNT, 
                         DOBYR, PLANKEY, STDPROV, WGTKEY, YEAR, AGE, DATATYP, PLANTYP, STDPLAC, LOINCCD, RESUNIT, EFAMID)
VALUES        (1903, NULL, N'L', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('12-20-2012' as Date), NULL, NULL, NULL, NULL, NULL, 5, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'56784-2', NULL, NULL)

/*1904 - Patient has Result NE 0 and > -99999999.99999; result listed in value_as_number field*/
INSERT [dbo].[LAB](ENROLID, SEQNUM, ABNORMAL, AGEGRP, EECLASS, EESTATU, EIDFLAG, EMPREL, ENRFLAG, HLTHPLAN, INDSTRY, MHSACOVG, PHYFLAG, PROCTYP, 
                         REGION, RX, SEX, EGEOLOC, MDC, VERSION, RESLTCAT, DX1, PROC1, PDDATE, SVCDATE, MSA, ORDERID, PROVID, REFHIGH, REFLOW, RESULT, TESTCNT, 
                         DOBYR, PLANKEY, STDPROV, WGTKEY, YEAR, AGE, DATATYP, PLANTYP, STDPLAC, LOINCCD, RESUNIT, EFAMID)
VALUES        (1904, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('08-24-2012' as Date), NULL, NULL, NULL, NULL, NULL, 120, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'56789-1', NULL, NULL)