/*CCAE Sprint 6 Test Cases Table 15 Observation*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their observations will not come through*/

/*1501*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1501,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1502*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1502,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1503*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1503,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1504*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1504,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1505*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1505,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*1506*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1506,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)


/*1501 - SVCDATE is outside of observation_period; observation record is created*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, 20.0, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1501, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('10-13-2013' as Date), NULL)

/*1502 - BMI is only question answered, BMI is only record created in observation*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, 28.6, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1502, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('09-22-2012' as Date), NULL)

/*1503 - Patient answered 3 for question CGTDUR, value_as_string = '11-20', value_as_number=3*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1503, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('05-25-2012' as Date), NULL)


/*1504 - Patient has weight 201, value_as_string = null, value_as_number=201*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1504, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 201, NULL, NULL, NULL, NULL, Cast ('07-16-2012' as Date), NULL)

/*1505 - Patient has 1 in CC_ASTHMA column, observation_source_value='Self-reported Asthma'*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, 1, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1505, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('09-13-2012' as Date), NULL)

/*1506 - Patient has 2 in CGTPKAMT column, observation_source_value='1 pack per day or more'*/
INSERT [dbo].[HEALTH_RISK_ASSESSMENT] (ALC_AMT, ALCDYAMT, ALCWEEK, BMI, CC_ALLERGY, CC_ARTHRITIS, CC_ASTHMA, CC_BACKPAIN, CC_CHF, CC_DEPRESS, 
                         CC_DIAB, CC_HEARTDIS, CC_HIGHBP, CC_HIGHCOL, CC_HRTBURN, CC_LUNGDIS, CC_MIGRAINE, CC_NONSKINCAN, CC_OSTEOPO, CC_SKINCAN, CGRAMT, 
                         CGRCURR, CGRDUR, CGRPREV, CGRQTYR, CGRQUIT, CGTAMT, CGTCURR, CGTDUR, CGTPKAMT, CGTPREV, CGTQTCAT, CGTQTYR, CGTQUIT, CHEWAMT, 
                         CHEWCURR, CHEWDUR, CHEWPREV, CHEWQTYR, CHEWQUIT, CHOLESTR, COPESTRS, DIAST_BP, DIETFRT, DIETFRVG, DIETVEG, DOBYR, DRNKDRV, 
                         EDUC_LVL, ENROLID, EXERMO, EXERWEEK, FAMABSCAT12, FIREEXT, FLU_SHOT, GLUCOSE, HDL, HEIGHT, HLTIMPCT, JOB_SAT, LDL, LIFE_SAT, LIFTWGT, 
                         MH_FREQ, MH_PROB, PIPEAMT, PIPECURR, PIPEDUR, PIPEPREV, PIPEQTYR, PIPEQUIT, PLANALC, PLANDIET, PLANDRAD, PLANEXER, PLANSLP, PLANSTRS, 
                         PLANTOB, PLANWGT, PREV_MAMMO, PREV_PAPTEST, PREV_SIGMOID, PRODABSCAT, RISK_ALC, RISK_BP, RISK_CHOL, RISK_EXER, RISK_GLUC, RISK_MH, 
                         RISK_NUTR, RISK_SAFE, RISK_SLEEP, RISK_SMOK, RISK_WGT, SEATBELT, SELFHLTH, SEQNUM, SEX, SLPAPNEA, SLPPROB, SMKDETECT, STRETCH, 
                         SYSTO_BP, TOBCURR, TOBPREV, TRIGLYCD, VERSION, WEIGHT, WORKABS, WRKABSCAT, WRKABSCAT12, YEAR, SURVDATE, PREV_PROSTEX)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, 1506, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast ('03-14-2012' as Date), NULL)