/*CCAE Sprint 6 Test Cases Table 14 Drug Cost*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their drug eras will not come through*/

/*1401*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1401,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1402*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1402,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)


/*1401 - Cost is associated with a drug claim; costs are reported correctly*/
INSERT [dbo].[DRUG_CLAIMS](AGE, AGEGRP, AWP, CAP_SVC, COB, COINS, COPAY, DATATYP, DAWIND, DAYSUPP, DEACLAS, DEDUCT, DISPFEE, DOBYR, EECLASS, 
        EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, GENERID, GENIND, HLTHPLAN, INDSTRY, INGCOST, MAINTIN, METQTY, MHSACOVG, MSA, 
        NDCNUM, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PHARMID, PHYFLAG, PLANKEY, PLANTYP, QTY, REFILL, REGION, RXMR, SALETAX, SEQNUM, SEX, 
        SVCDATE, THERCLS, THERGRP, VERSION, WGTKEY, YEAR, EFAMID)
VALUES (NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, 210, NULL, NULL, NULL, 
        NULL, NULL, NULL, NULL, NULL, 1401, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        right('00'+ '00463303410',11), NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
        Cast ('03-15-2012' as date), NULL, NULL, NULL, NULL, 2012, NULL)

/*1402 - Procedure is mapped to drug, cost is written to procedure cost*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, 25, NULL, 312, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 1402, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'90649', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-08-21' as Date), 
                         NULL, Cast('2012-08-21' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 14021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1402, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'90649', NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-08-21' as Date), Cast('2012-08-21' as Date), NULL, NULL, 2012, NULL)
