/*CCAE Sprint 6 Test Cases Table 10 Procedure Cost*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their procedure costs will not come through*/

/*1001*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 1001,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*1002*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1002,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*1003*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	1003,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)

/*Insert values into inpatient_services, outpatient_Services, facility_header and inpatient_admissions to create procedure_cost records (procedure_occurrence records will also be created by default)*/

/*1001*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 10011, 120, 32, 10, NULL, 25, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1001, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'76872', NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-11-21' as Date), NULL, Cast('2012-11-22' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES       (NULL, NULL, NULL, NULL, 10011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1001, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL)

/*1002*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, 100, 200, 300, NULL, 400, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 1002, 8901, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'25900', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-10-01' as Date), 
                         NULL, Cast('2012-10-01' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 10021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1002, 8901, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-10-01' as Date), Cast('2012-10-01' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, 101, 201, 301, NULL, 401, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 1002, 7890, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'32856', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-10-02' as Date), 
                         NULL, Cast('2012-10-02' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 10021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1002, 7890, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-10-02' as Date), Cast('2012-10-02' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, 102, 202, 302, NULL, 402, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 1002, 6789, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'67800', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-10-03' as Date), 
                         NULL, Cast('2012-10-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 10021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1002, 6789, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-10-03' as Date), Cast('2012-10-03' as Date), NULL, NULL, 2012, NULL)

/*1003*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, 103, 203, 303, NULL, 403, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 1003, 2222, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-10-04' as Date), 
                         NULL, Cast('2012-10-04' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 10031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1003, 2222, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-10-04' as Date), Cast('2012-10-04' as Date), NULL, NULL, 2012, NULL)
