{Source_to_Standard}
SELECT distinct SOURCE_CODE, TARGET_CONCEPT_ID
FROM CTE_VOCAB_MAP
WHERE lower(SOURCE_VOCABULARY_ID) in ('gemscript', 'jnj_cprd_gs_rxn') AND (lower(TARGET_VOCABULARY_ID)='multilex' OR lower(TARGET_VOCABULARY_ID)='rxnorm') 
AND lower(TARGET_DOMAIN_ID)='drug' AND (TARGET_INVALID_REASON is NULL or TARGET_INVALID_REASON = '')