SELECT DISTINCT 
	ca.DESCENDANT_CONCEPT_ID /*this is where you set the DRUG_EXPOSURE.DRUG_CONCEPT_ID to*/,
   ca.ANCESTOR_CONCEPT_ID /*ingredient level*/
FROM CONCEPT c1	
	JOIN CONCEPT_ANCESTOR ca
		ON ca.DESCENDANT_CONCEPT_ID = c1.CONCEPT_ID
	JOIN CONCEPT c2	
		ON c2.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
		AND c2.VOCABULARY_ID in (8,22) 
		AND c2.CONCEPT_LEVEL = 2
WHERE c1.VOCABULARY_ID in (8 , 22)
