/*
SELECT 'DROP TABLE ' + TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME + ';'
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE='BASE TABLE'
AND TABLE_SCHEMA = 'cdm_testing_mdcd'

*/

SELECT *
FROM TESTING.CDM_TESTING_MDCD.TEST_RESULTS
--WHERE DESCRIPTION LIKE '%1431%'
WHERE STATUS = 'FAIL'


DECLARE @PERSON_ID BIGINT
SET @PERSON_ID = 23

SELECT *
FROM NATIVE.CDM_TESTING_MDCD.ENROLLMENT_DETAIL
WHERE ENROLID = @PERSON_ID

SELECT *
FROM NATIVE.CDM_TESTING_MDCD.INPATIENT_SERVICES
WHERE ENROLID = @PERSON_ID


--SELECT *
--FROM NATIVE.CDM_TESTING_MDCD.LAB
--WHERE ENROLID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.PERSON
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.VISIT_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.CONDITION_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.CONDITION_ERA
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.DRUG_EXPOSURE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.PROCEDURE_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.MEASUREMENT
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.DEATH
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_MDCD.COST



