SELECT  DISTINCT SOURCE_CODE, TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP 
WHERE TARGET_VOCABULARY_ID = 43
		AND SOURCE_VOCABULARY_ID = 43
		AND (INVALID_REASON IS NULL or INVALID_REASON = '')
		AND PRIMARY_MAP = 'Y'
		AND GETDATE() BETWEEN VALID_START_DATE AND VALID_END_DATE
