/*
SELECT 'DROP TABLE ' + TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME + ';'
FROM INFORMATION_SCHEMA.TABLES 
WHERE TABLE_TYPE='BASE TABLE'
AND TABLE_SCHEMA = 'cdm_testing_CCAE'

*/

SELECT *
FROM TESTING.CDM_TESTING_MDCR.TEST_RESULTS
--WHERE TEST LIKE '%cost%'
WHERE DESCRIPTION LIKE '%1515%'
WHERE STATUS = 'FAIL'


DECLARE @PERSON_ID BIGINT
SET @PERSON_ID = 189

SELECT *
FROM NATIVE.CDM_TESTING_CCAE.ENROLLMENT_DETAIL
WHERE ENROLID = @PERSON_ID

SELECT *
FROM NATIVE.CDM_TESTING_CCAE.INPATIENT_SERVICES
WHERE ENROLID = @PERSON_ID


--SELECT *
--FROM NATIVE.CDM_TESTING_CCAE.LAB
--WHERE ENROLID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.PERSON
WHERE PERSON_ID = @PERSON_ID

SELECT VISIT_OCCURRENCE_ID, PERSON_ID, VISIT_CONCEPT_ID, VISIT_START_DATE, VISIT_END_DATE, PRECEDING_VISIT_OCCURRENCE_ID
FROM TESTING.CDM_TESTING_CCAE.VISIT_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.CONDITION_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.CONDITION_ERA
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.DRUG_EXPOSURE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.PROCEDURE_OCCURRENCE
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.MEASUREMENT
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.DEATH
WHERE PERSON_ID = @PERSON_ID

SELECT *
FROM TESTING.CDM_TESTING_CCAE.COST




