IF OBJECT_ID('testing.Cdm_Testing_nhanes.test_results', 'U') IS NOT NULL DROP TABLE testing.Cdm_Testing_nhanes.test_results;

CREATE TABLE testing.Cdm_Testing_nhanes.test_results (id INT, description VARCHAR(512), cdm_pid INT, source_pid INT, test VARCHAR(256), status VARCHAR(5));

-- 2: Hospital has caresetting_id  47
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 2 AS id, 'Hospital has caresetting_id  47' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect care_site' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.care_site WHERE place_of_service_concept_id = '0' AND care_site_source_value = '1' AND place_of_service_source_value = '47') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 3: Hospital has caresetting_id  86
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 3 AS id, 'Hospital has caresetting_id  86' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect care_site' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.care_site WHERE place_of_service_concept_id = '8676' AND care_site_source_value = '5' AND place_of_service_source_value = '86') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 4: Hospital has caresetting_id  140
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 4 AS id, 'Hospital has caresetting_id  140' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect care_site' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.care_site WHERE place_of_service_concept_id = '4305525' AND care_site_source_value = '9' AND place_of_service_source_value = '140') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 5: Hospital has caresetting_id  14
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 5 AS id, 'Hospital has caresetting_id  14' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect care_site' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.care_site WHERE place_of_service_concept_id = '45756805' AND care_site_source_value = '13' AND place_of_service_source_value = '14') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 6: Patient has diagnosis in hf_f_diagnosis
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 6 AS id, 'Patient has diagnosis in hf_f_diagnosis' AS description, 17 AS cdm_pid, '17' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '17' AND condition_concept_id = '40487064' AND condition_type_concept_id = '38000200') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 7: Patient has diagnosis in hf_f_diagnosis
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 7 AS id, 'Patient has diagnosis in hf_f_diagnosis' AS description, 20 AS cdm_pid, '20' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '20' AND condition_concept_id = '46270403' AND condition_type_concept_id = '38000230') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 8: Patient has code in hf_f_clinical_event that maps to domain = Condition midnight
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 8 AS id, 'Patient has code in hf_f_clinical_event that maps to domain = Condition midnight' AS description, 23 AS cdm_pid, '23' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '23' AND condition_concept_id = '27674' AND condition_type_concept_id = '45754805') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 9: Patient has code in hf_f_clinical_event that maps to domain = Condition
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 9 AS id, 'Patient has code in hf_f_clinical_event that maps to domain = Condition' AS description, 26 AS cdm_pid, '26' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '26' AND condition_concept_id = '27674' AND condition_type_concept_id = '45754805') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 10: Patient has code in hf_f_clinical_event that maps to domain = Condition, lab_procedure_id is blank
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 10 AS id, 'Patient has code in hf_f_clinical_event that maps to domain = Condition, lab_procedure_id is blank' AS description, 29 AS cdm_pid, '29' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '29' AND condition_concept_id = '27674' AND condition_type_concept_id = '45754805') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 11: Patient has HCPCS code in hf_f_procedure that maps to domain = Condition midnight
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 11 AS id, 'Patient has HCPCS code in hf_f_procedure that maps to domain = Condition midnight' AS description, 32 AS cdm_pid, '32' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '32' AND condition_concept_id = '201820' AND condition_start_date = '2000-08-29' AND condition_type_concept_id = '38000251') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 12: Patient has HCPCS code in hf_f_procedure that maps to domain = Condition time outside encounter
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 12 AS id, 'Patient has HCPCS code in hf_f_procedure that maps to domain = Condition time outside encounter' AS description, 35 AS cdm_pid, '35' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '35' AND condition_concept_id = '201820' AND condition_start_date = '2000-08-29' AND condition_type_concept_id = '38000251') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 13: Patient has HCPCS code in hf_f_procedure that maps to domain = Condition time inside encounter
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 13 AS id, 'Patient has HCPCS code in hf_f_procedure that maps to domain = Condition time inside encounter' AS description, 38 AS cdm_pid, '38' AS source_pid, 'Expect condition_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.condition_occurrence WHERE person_id = '38' AND condition_concept_id = '201820' AND condition_start_date = '2000-08-29' AND condition_type_concept_id = '38000251') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 14: Patient has drug in hf_f_medication
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 14 AS id, 'Patient has drug in hf_f_medication' AS description, 41 AS cdm_pid, '41' AS source_pid, 'Expect drug_exposure' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.drug_exposure WHERE person_id = '41' AND drug_concept_id = '40175105' AND drug_exposure_start_date = '2011-03-29' AND drug_source_value = '52604520002' AND drug_source_concept_id = '44900017') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 15: Patient has drug code in hf_f_procedure
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 15 AS id, 'Patient has drug code in hf_f_procedure' AS description, 44 AS cdm_pid, '44' AS source_pid, 'Expect drug_exposure' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.drug_exposure WHERE person_id = '44' AND drug_concept_id = '42479709' AND drug_exposure_start_date = '2012-05-07') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 16: Hospital has census_division code 1
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 16 AS id, 'Hospital has census_division code 1' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(CT, ME, MA, NH, RI, VT)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 17: Hospital has census_division code 2
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 17 AS id, 'Hospital has census_division code 2' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(NJ, NY, PA)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 18: Hospital has census_division code 3
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 18 AS id, 'Hospital has census_division code 3' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(IA, KS, MN, MO, ND, SD)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 19: Hospital has census_division code 4
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 19 AS id, 'Hospital has census_division code 4' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(IL, IN, MI, OH, WI)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 20: Hospital has census_division code 5
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 20 AS id, 'Hospital has census_division code 5' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(AL, KY, MS, TN)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 21: Hospital has census_division code 6
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 21 AS id, 'Hospital has census_division code 6' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(DE, DC, FL, GA, MD, NC, SC, VA, WV)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 22: Hospital has census_division code 7
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 22 AS id, 'Hospital has census_division code 7' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(AR, LA, OK, TX)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 23: Hospital has census_division code 8
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 23 AS id, 'Hospital has census_division code 8' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(AZ, CO, ID, MT, NV, NM, UT, WY)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 24: Hospital has census_division code 9
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 24 AS id, 'Hospital has census_division code 9' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect location' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.location WHERE location_source_value = '(AK, CA, HI, OR, WA)') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 25: Patient has measurement in lab procedure table
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 25 AS id, 'Patient has measurement in lab procedure table' AS description, 56 AS cdm_pid, '56' AS source_pid, 'Expect measurement' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.measurement WHERE person_id = '56' AND measurement_concept_id = '40760809' AND measurement_date = '2012-05-07' AND measurement_type_concept_id = '44818702') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 26: Patient has two encounters 0 days apart, one observation_period created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 26 AS id, 'Patient has two encounters 0 days apart, one observation_period created' AS description, 59 AS cdm_pid, '59' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '59' AND observation_period_start_date = '1/16/2010' AND observation_period_end_date = '1/22/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 27: Patient has two encounters 3 days apart, two observation_periods created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 27 AS id, 'Patient has two encounters 3 days apart, two observation_periods created' AS description, 63 AS cdm_pid, '63' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '63' AND observation_period_start_date = '1/16/2010' AND observation_period_end_date = '1/20/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 27 AS id, 'Patient has two encounters 3 days apart, two observation_periods created' AS description, 63 AS cdm_pid, '63' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '63' AND observation_period_start_date = '1/23/2010' AND observation_period_end_date = '1/25/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 28: Patient has one encounter across the end of a year, one observation_period created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 28 AS id, 'Patient has one encounter across the end of a year, one observation_period created' AS description, 67 AS cdm_pid, '67' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '67' AND observation_period_start_date = '12/14/2015' AND observation_period_end_date = '1/07/2016') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 29: Patient has 3 encounters 3 across 3 months, 3 observation_periods created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 29 AS id, 'Patient has 3 encounters 3 across 3 months, 3 observation_periods created' AS description, 70 AS cdm_pid, '70' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '70' AND observation_period_start_date = '05/05/2010' AND observation_period_end_date = '05/16/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 29 AS id, 'Patient has 3 encounters 3 across 3 months, 3 observation_periods created' AS description, 70 AS cdm_pid, '70' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '70' AND observation_period_start_date = '07/02/2010' AND observation_period_end_date = '07/16/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 29 AS id, 'Patient has 3 encounters 3 across 3 months, 3 observation_periods created' AS description, 70 AS cdm_pid, '70' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '70' AND observation_period_start_date = '06/03/2010' AND observation_period_end_date = '07/01/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 30: Patient has one encounter 0 days apart, one observation_period created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 30 AS id, 'Patient has one encounter 0 days apart, one observation_period created' AS description, 75 AS cdm_pid, '75' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '75' AND observation_period_start_date = '02/02/2000' AND observation_period_end_date = '02/02/2000') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 31: Patient has one encounter 1 day apart, one observation_period created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 31 AS id, 'Patient has one encounter 1 day apart, one observation_period created' AS description, 78 AS cdm_pid, '78' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '78' AND observation_period_start_date = '03/22/2002' AND observation_period_end_date = '03/22/2002') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 32: Patient has two encounters 3 months apart, two observation_periods created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 32 AS id, 'Patient has two encounters 3 months apart, two observation_periods created' AS description, 81 AS cdm_pid, '81' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '81' AND observation_period_start_date = '09/08/2006' AND observation_period_end_date = '09/10/2006') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 32 AS id, 'Patient has two encounters 3 months apart, two observation_periods created' AS description, 81 AS cdm_pid, '81' AS source_pid, 'Expect observation_period' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation_period WHERE person_id = '81' AND observation_period_start_date = '06/02/2006' AND observation_period_end_date = '06/06/2006') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 33: Patient has observation code in hf_f_clinical_event
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 33 AS id, 'Patient has observation code in hf_f_clinical_event' AS description, 85 AS cdm_pid, '85' AS source_pid, 'Expect observation' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation WHERE person_id = '85' AND observation_concept_id = '21494887') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 34: Patient has code in hf_f_clinical_event that maps to domain = Observation
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 34 AS id, 'Patient has code in hf_f_clinical_event that maps to domain = Observation' AS description, 88 AS cdm_pid, '88' AS source_pid, 'Expect observation' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation WHERE person_id = '88' AND observation_concept_id = '4201235') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 35: Patient has observation code in hf_f_diagnosis
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 35 AS id, 'Patient has observation code in hf_f_diagnosis' AS description, 91 AS cdm_pid, '91' AS source_pid, 'Expect observation' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.observation WHERE person_id = '91' AND observation_concept_id = '435134') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 36: Patient has gender = Male
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 36 AS id, 'Patient has gender = Male' AS description, 94 AS cdm_pid, '94' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '94' AND gender_concept_id = '8507' AND gender_source_value = 'Male') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 37: Patient has gender = Female
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 37 AS id, 'Patient has gender = Female' AS description, 97 AS cdm_pid, '97' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '97' AND gender_concept_id = '8532' AND gender_source_value = 'Female') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 38: Patient has an unknown gender on their most recent record
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 38 AS id, 'Patient has an unknown gender on their most recent record' AS description, 100 AS cdm_pid, '100' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '100') != 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 39: Patient has race value Caucasian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 39 AS id, 'Patient has race value Caucasian' AS description, 105 AS cdm_pid, '105' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '105' AND race_concept_id = '8527' AND race_source_value = 'Caucasian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 40: Patient has race value African American
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 40 AS id, 'Patient has race value African American' AS description, 108 AS cdm_pid, '108' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '108' AND race_concept_id = '8516' AND race_source_value = 'African American') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 41: Patient has race value Hispanic
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 41 AS id, 'Patient has race value Hispanic' AS description, 111 AS cdm_pid, '111' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '111' AND race_concept_id = '0' AND race_source_value = 'Hispanic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 42: Patient has race value Asian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 42 AS id, 'Patient has race value Asian' AS description, 114 AS cdm_pid, '114' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '114' AND race_concept_id = '8515' AND race_source_value = 'Asian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 43: Patient has race value Native American
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 43 AS id, 'Patient has race value Native American' AS description, 117 AS cdm_pid, '117' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '117' AND race_concept_id = '8657' AND race_source_value = 'Native American') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 44: Patient has race value Biracial
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 44 AS id, 'Patient has race value Biracial' AS description, 120 AS cdm_pid, '120' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '120' AND race_concept_id = '0' AND race_source_value = 'Biracial') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 45: Patient has race value Pacific Islander
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 45 AS id, 'Patient has race value Pacific Islander' AS description, 123 AS cdm_pid, '123' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '123' AND race_concept_id = '38003613' AND race_source_value = 'Pacific Islander') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 46: Patient has race value Asian/Pacific Islander
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 46 AS id, 'Patient has race value Asian/Pacific Islander' AS description, 126 AS cdm_pid, '126' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '126' AND race_concept_id = '38003613' AND race_source_value = 'Asian/Pacific Islander') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 47: Patient has race value Mid Eastern Indian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 47 AS id, 'Patient has race value Mid Eastern Indian' AS description, 129 AS cdm_pid, '129' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '129' AND race_concept_id = '38003615' AND race_source_value = 'Mid Eastern Indian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 48: Patient has race value Other
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 48 AS id, 'Patient has race value Other' AS description, 132 AS cdm_pid, '132' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '132' AND race_concept_id = '0' AND race_source_value = 'Other') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 49: Patient has ethnicity value Caucasian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 49 AS id, 'Patient has ethnicity value Caucasian' AS description, 135 AS cdm_pid, '135' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '135' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Caucasian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 50: Patient has ethnicity value African American
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 50 AS id, 'Patient has ethnicity value African American' AS description, 138 AS cdm_pid, '138' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '138' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'African American') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 51: Patient has ethnicity value Hispanic
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 51 AS id, 'Patient has ethnicity value Hispanic' AS description, 141 AS cdm_pid, '141' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '141' AND ethnicity_concept_id = '38003563' AND ethnicity_source_value = 'Hispanic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 52: Patient has ethnicity value Asian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 52 AS id, 'Patient has ethnicity value Asian' AS description, 144 AS cdm_pid, '144' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '144' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Asian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 53: Patient has ethnicity value Native American
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 53 AS id, 'Patient has ethnicity value Native American' AS description, 147 AS cdm_pid, '147' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '147' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Native American') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 54: Patient has ethnicity value Biracial
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 54 AS id, 'Patient has ethnicity value Biracial' AS description, 150 AS cdm_pid, '150' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '150' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Biracial') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 55: Patient has ethnicity value Pacific Islander
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 55 AS id, 'Patient has ethnicity value Pacific Islander' AS description, 153 AS cdm_pid, '153' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '153' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Pacific Islander') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 56: Patient has ethnicity value Asian/Pacific Islander
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 56 AS id, 'Patient has ethnicity value Asian/Pacific Islander' AS description, 156 AS cdm_pid, '156' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '156' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Asian/Pacific Islander') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 57: Patient has ethnicity value Mid Eastern Indian
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 57 AS id, 'Patient has ethnicity value Mid Eastern Indian' AS description, 159 AS cdm_pid, '159' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '159' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Mid Eastern Indian') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 58: Patient has ethnicity value Other
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 58 AS id, 'Patient has ethnicity value Other' AS description, 162 AS cdm_pid, '162' AS source_pid, 'Expect person' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.person WHERE person_id = '162' AND ethnicity_concept_id = '38003564' AND ethnicity_source_value = 'Other') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 59: Patient has ICD10PCS code in hf_f_procedure and procedure priority = 1
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 59 AS id, 'Patient has ICD10PCS code in hf_f_procedure and procedure priority = 1' AS description, 165 AS cdm_pid, '165' AS source_pid, 'Expect procedure_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.procedure_occurrence WHERE person_id = '165' AND procedure_concept_id = '2729909' AND procedure_date = '2012-05-07' AND procedure_type_concept_id = '38000251') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 60: Patient has CPT4 code in hf_f_procedure and procedure priority = 3
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 60 AS id, 'Patient has CPT4 code in hf_f_procedure and procedure priority = 3' AS description, 168 AS cdm_pid, '168' AS source_pid, 'Expect procedure_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.procedure_occurrence WHERE person_id = '168' AND procedure_concept_id = '2108329' AND procedure_date = '2012-05-12' AND procedure_type_concept_id = '38000271') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 61: Patient has procedure code in hf_f_clinical_event
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 61 AS id, 'Patient has procedure code in hf_f_clinical_event' AS description, 171 AS cdm_pid, '171' AS source_pid, 'Expect procedure_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.procedure_occurrence WHERE person_id = '171' AND procedure_concept_id = '2007077' AND procedure_type_concept_id = '45754805') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 62: Patient has procedure code in hf_f_diagnosis
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 62 AS id, 'Patient has procedure code in hf_f_diagnosis' AS description, 174 AS cdm_pid, '174' AS source_pid, 'Expect procedure_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.procedure_occurrence WHERE person_id = '174' AND procedure_concept_id = '4064902') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 63: Provider has medical specialty Internal Medicine
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 63 AS id, 'Provider has medical specialty Internal Medicine' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '177' AND specialty_concept_id = '38004456' AND specialty_source_value = 'Internal Medicine') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 64: Provider has medical specialty Not a Medical Speciality
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 64 AS id, 'Provider has medical specialty Not a Medical Speciality' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '178' AND specialty_concept_id = '38004514' AND specialty_source_value = 'Not a Medical Speciality') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 65: Provider has medical specialty Family/General Practice
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 65 AS id, 'Provider has medical specialty Family/General Practice' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '179' AND specialty_concept_id = '38004453' AND specialty_source_value = 'Family/General Practice') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 66: Provider has medical specialty Other
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 66 AS id, 'Provider has medical specialty Other' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '180' AND specialty_concept_id = '38004514' AND specialty_source_value = 'Other') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 67: Provider has medical specialty Undefined / Unknown
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 67 AS id, 'Provider has medical specialty Undefined / Unknown' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '181' AND specialty_concept_id = '38004514' AND specialty_source_value = 'Undefined / Unknown') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 68: Provider has medical specialty Pediatrics
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 68 AS id, 'Provider has medical specialty Pediatrics' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '182' AND specialty_concept_id = '38004477' AND specialty_source_value = 'Pediatrics') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 69: Provider has medical specialty Emergency/Trauma
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 69 AS id, 'Provider has medical specialty Emergency/Trauma' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '183' AND specialty_concept_id = '38004510' AND specialty_source_value = 'Emergency/Trauma') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 70: Provider has medical specialty Radiology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 70 AS id, 'Provider has medical specialty Radiology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '184' AND specialty_concept_id = '45756825' AND specialty_source_value = 'Radiology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 71: Provider has medical specialty Obstetrics and Gynecology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 71 AS id, 'Provider has medical specialty Obstetrics and Gynecology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '185' AND specialty_concept_id = '38004461' AND specialty_source_value = 'Obstetrics and Gynecology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 72: Provider has medical specialty Anesthesiology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 72 AS id, 'Provider has medical specialty Anesthesiology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '186' AND specialty_concept_id = '38004450' AND specialty_source_value = 'Anesthesiology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 73: Provider has medical specialty Surgery, General
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 73 AS id, 'Provider has medical specialty Surgery, General' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '187' AND specialty_concept_id = '38004447' AND specialty_source_value = 'Surgery, General') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 74: Provider has medical specialty DCPTEAM
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 74 AS id, 'Provider has medical specialty DCPTEAM' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '188' AND specialty_concept_id = '38004514' AND specialty_source_value = 'DCPTEAM') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 75: Provider has medical specialty Orthopedics
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 75 AS id, 'Provider has medical specialty Orthopedics' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '189' AND specialty_concept_id = '38004465' AND specialty_source_value = 'Orthopedics') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 76: Provider has medical specialty Cardiology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 76 AS id, 'Provider has medical specialty Cardiology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '190' AND specialty_concept_id = '38004451' AND specialty_source_value = 'Cardiology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 77: Provider has medical specialty Radiologist
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 77 AS id, 'Provider has medical specialty Radiologist' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '191' AND specialty_concept_id = '45756825' AND specialty_source_value = 'Radiologist') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 78: Provider has medical specialty Psychiatry
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 78 AS id, 'Provider has medical specialty Psychiatry' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '192' AND specialty_concept_id = '38004469' AND specialty_source_value = 'Psychiatry') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 79: Provider has medical specialty Gastroenterology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 79 AS id, 'Provider has medical specialty Gastroenterology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '193' AND specialty_concept_id = '38004455' AND specialty_source_value = 'Gastroenterology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 80: Provider has medical specialty Ophthalmology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 80 AS id, 'Provider has medical specialty Ophthalmology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '194' AND specialty_concept_id = '38004463' AND specialty_source_value = 'Ophthalmology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 81: Provider has medical specialty Neurology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 81 AS id, 'Provider has medical specialty Neurology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '195' AND specialty_concept_id = '38004458' AND specialty_source_value = 'Neurology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 82: Provider has medical specialty Dentistry
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 82 AS id, 'Provider has medical specialty Dentistry' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '196' AND specialty_concept_id = '43125856' AND specialty_source_value = 'Dentistry') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 83: Provider has medical specialty Urology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 83 AS id, 'Provider has medical specialty Urology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '197' AND specialty_concept_id = '38004474' AND specialty_source_value = 'Urology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 84: Provider has medical specialty Family Practice
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 84 AS id, 'Provider has medical specialty Family Practice' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '198' AND specialty_concept_id = '38004453' AND specialty_source_value = 'Family Practice') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 85: Provider has medical specialty Gynecology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 85 AS id, 'Provider has medical specialty Gynecology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '199' AND specialty_concept_id = '38004461' AND specialty_source_value = 'Gynecology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 86: Provider has medical specialty Otolaryngology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 86 AS id, 'Provider has medical specialty Otolaryngology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '200' AND specialty_concept_id = '38004449' AND specialty_source_value = 'Otolaryngology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 87: Provider has medical specialty Obstetrics
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 87 AS id, 'Provider has medical specialty Obstetrics' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '201' AND specialty_concept_id = '38004461' AND specialty_source_value = 'Obstetrics') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 88: Provider has medical specialty Hematology/Oncology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 88 AS id, 'Provider has medical specialty Hematology/Oncology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '202' AND specialty_concept_id = '38004502' AND specialty_source_value = 'Hematology/Oncology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 89: Provider has medical specialty Pulmonology
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 89 AS id, 'Provider has medical specialty Pulmonology' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '203' AND specialty_concept_id = '38004472' AND specialty_source_value = 'Pulmonology') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 90: Provider has medical specialty Student
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 90 AS id, 'Provider has medical specialty Student' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '204' AND specialty_concept_id = '4277918' AND specialty_source_value = 'Student') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 91: Provider has medical specialty Podiatry
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 91 AS id, 'Provider has medical specialty Podiatry' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '205' AND specialty_concept_id = '38004486' AND specialty_source_value = 'Podiatry') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 92: Provider has medical specialty Surgeon
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 92 AS id, 'Provider has medical specialty Surgeon' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '206' AND specialty_concept_id = '38004447' AND specialty_source_value = 'Surgeon') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 93: Provider has medical specialty Orthopedics, Reconstructive
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 93 AS id, 'Provider has medical specialty Orthopedics, Reconstructive' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '207' AND specialty_concept_id = '38004465' AND specialty_source_value = 'Orthopedics, Reconstructive') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 94: Provider has medical specialty Surgery, Plastic
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 94 AS id, 'Provider has medical specialty Surgery, Plastic' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '208' AND specialty_concept_id = '38004467' AND specialty_source_value = 'Surgery, Plastic') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 95: Provider has medical specialty Hospitalist
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 95 AS id, 'Provider has medical specialty Hospitalist' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '209' AND specialty_concept_id = '38004515' AND specialty_source_value = 'Hospitalist') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 96: Provider has medical specialty Health Care Provider
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 96 AS id, 'Provider has medical specialty Health Care Provider' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '210' AND specialty_concept_id = '38004514' AND specialty_source_value = 'Health Care Provider') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 97: Provider has medical specialty Surgery, Neuro
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 97 AS id, 'Provider has medical specialty Surgery, Neuro' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '211' AND specialty_concept_id = '38004459' AND specialty_source_value = 'Surgery, Neuro') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 98: Provider has medical Physical Medicine and Rehabilitation
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 98 AS id, 'Provider has medical Physical Medicine and Rehabilitation' AS description, NULL AS cdm_pid, NULL AS source_pid, 'Expect provider' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.provider WHERE provider_id = '212' AND specialty_concept_id = '38004468' AND specialty_source_value = 'Physical Medicine And Rehabilitation') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 99: Patient has two IP encounters 0 days apart, one visit created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 99 AS id, 'Patient has two IP encounters 0 days apart, one visit created' AS description, 213 AS cdm_pid, '213' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '213' AND visit_concept_id = '9201' AND visit_start_date = '1/16/2010' AND visit_end_date = '1/22/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 100: Patient has two IP encounters >0 days apart, two visits created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 100 AS id, 'Patient has two IP encounters >0 days apart, two visits created' AS description, 217 AS cdm_pid, '217' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '217' AND visit_concept_id = '9201' AND visit_start_date = '1/16/2010' AND visit_end_date = '1/20/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 100 AS id, 'Patient has two IP encounters >0 days apart, two visits created' AS description, 217 AS cdm_pid, '217' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '217' AND visit_concept_id = '9201' AND visit_start_date = '1/25/2010' AND visit_end_date = '1/27/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 101: Patient has two IP encounters 0 days apart, one visit created with the earlier physician id
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 101 AS id, 'Patient has two IP encounters 0 days apart, one visit created with the earlier physician id' AS description, 221 AS cdm_pid, '221' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '221' AND visit_concept_id = '9201' AND visit_start_date = '1/16/2010' AND visit_end_date = '1/22/2010' AND provider_id = '225') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 102: Patient has one IP encounter with an OP visit in the middle, one IP visit created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 102 AS id, 'Patient has one IP encounter with an OP visit in the middle, one IP visit created' AS description, 227 AS cdm_pid, '227' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '227' AND visit_concept_id = '9201' AND visit_start_date = '2/16/2010' AND visit_end_date = '2/20/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
-- 103: Patient has one IP encounter with an ER visit at the beginning, one IP visit and one ER visit created
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 103 AS id, 'Patient has one IP encounter with an ER visit at the beginning, one IP visit and one ER visit created' AS description, 231 AS cdm_pid, '231' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '231' AND visit_concept_id = '9201' AND visit_start_date = '03/02/2010' AND visit_end_date = '3/05/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status
INSERT INTO testing.Cdm_Testing_nhanes.test_results SELECT 103 AS id, 'Patient has one IP encounter with an ER visit at the beginning, one IP visit and one ER visit created' AS description, 231 AS cdm_pid, '231' AS source_pid, 'Expect visit_occurrence' AS test, CASE WHEN(SELECT COUNT(*) FROM testing.Cdm_Testing_nhanes.visit_occurrence WHERE person_id = '231' AND visit_concept_id = '9203' AND visit_start_date = '03/02/2010' AND visit_end_date = '3/02/2010') = 0 THEN 'FAIL' ELSE 'PASS' END AS status