SELECT DISTINCT  REPLACE(SOURCE_CODE, '.', '') AS SOURCE_CODE,MIN(TARGET_CONCEPT_ID) TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP
WHERE 
TARGET_VOCABULARY_ID = 8 /*RXNORM*/
AND
SOURCE_VOCABULARY_ID in (3,4,5) /*ICD9 procedure/CPT4/HCPCS*/
AND PRIMARY_MAP = 'Y'
AND (INVALID_REASON IS NULL or INVALID_REASON = '')
GROUP BY REPLACE(SOURCE_CODE,'.','')
