IF OBJECT_ID('testing.cdm_testing_optumpan.test_results', 'U') IS NOT NULL DROP TABLE testing.cdm_testing_optumpan.test_results;
CREATE TABLE testing.cdm_testing_optumpan.test_results (id INT, description VARCHAR(512), test VARCHAR(256), status VARCHAR(5));
-- 0: Diagnosis without ''Diagnosis of'' status is not loaded
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 0 AS id, 'Diagnosis without ''Diagnosis of'' status is not loaded' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '1') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 1: Test diag_date to condition_start_date
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 1 AS id, 'Test diag_date to condition_start_date' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '2' AND condition_start_date = '2009-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 2: Test diagnosis code type ICD9
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 2 AS id, 'Test diagnosis code type ICD9' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '3' AND condition_concept_id = '141095' AND condition_source_value = '7061') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 3: Test diagnosis code type ICD10
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 3 AS id, 'Test diagnosis code type ICD10' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '5' AND condition_concept_id = '381850' AND condition_source_value = 'H44.611') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 4: Test primary diagnosis to condition_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 4 AS id, 'Test primary diagnosis to condition_type_concept_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '7' AND condition_type_concept_id = '44786627') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 5: Test non-primary diagnosis to condition_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 5 AS id, 'Test non-primary diagnosis to condition_type_concept_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '9' AND condition_type_concept_id = '44786629') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 6: Test diagnosis code with wrong diagnosis code type
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 6 AS id, 'Test diagnosis code with wrong diagnosis code type' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '11' AND condition_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 7: Test blank diagnosis code
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 7 AS id, 'Test blank diagnosis code' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '13' AND condition_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 8: Test HCPCS derived condition coming from procedure table
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 8 AS id, 'Test HCPCS derived condition coming from procedure table' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '15' AND condition_concept_id = '312327') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 9: Patient has PROCEDURE record; validate the provider for the encid is mapped to provid
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 9 AS id, 'Patient has PROCEDURE record; validate the provider for the encid is mapped to provid' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '16' AND provider_id = '17') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 10: Patient has PROCEDURE record; validate the visit_occurrence_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 10 AS id, 'Patient has PROCEDURE record; validate the visit_occurrence_id' AS description, 'Expect condition_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.condition_occurrence WHERE person_id = '19' AND visit_occurrence_id = '20') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 11: Patient is indicated dead by date_of_death. Their death date is the last day of the month.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 11 AS id, 'Patient is indicated dead by date_of_death. Their death date is the last day of the month.' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '22' AND death_date = '04/30/2014') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 12: Patient has diagnosis data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 12 AS id, 'Patient has diagnosis data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '24') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 13: Patient has encounter data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 13 AS id, 'Patient has encounter data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '27') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 14: Patient has immunizations data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 14 AS id, 'Patient has immunizations data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '30') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 15: Patient has insurance data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 15 AS id, 'Patient has insurance data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '33') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 16: Patient has labs data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 16 AS id, 'Patient has labs data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '36') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 17: Patient has medication_administrations data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 17 AS id, 'Patient has medication_administrations data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '39') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 18: Patient has microbiology data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 18 AS id, 'Patient has microbiology data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '42') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 19: Patient has nlp_biomarkers data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 19 AS id, 'Patient has nlp_biomarkers data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '45') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 20: Patient has nlp_drug_rationale data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 20 AS id, 'Patient has nlp_drug_rationale data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '48') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 21: Patient has nlp_measurement data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 21 AS id, 'Patient has nlp_measurement data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '51') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 22: Patient has nlp_sds data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 22 AS id, 'Patient has nlp_sds data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '54') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 23: Patient has nlp_sds_family data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 23 AS id, 'Patient has nlp_sds_family data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '57') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 24: Patient has observations data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 24 AS id, 'Patient has observations data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '60') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 25: Patient has patient_reported_medications data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 25 AS id, 'Patient has patient_reported_medications data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '63') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 26: Patient has prescriptions_written data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 26 AS id, 'Patient has prescriptions_written data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '66') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 27: Patient has procedure data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 27 AS id, 'Patient has procedure data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '69') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 28: Patient has visit data occurring data occurring exactly 30 days after death event. Expected result: dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 28 AS id, 'Patient has visit data occurring data occurring exactly 30 days after death event. Expected result: dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '72') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 29: Patient has diagnosis data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 29 AS id, 'Patient has diagnosis data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '75') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 30: Patient has encounter data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 30 AS id, 'Patient has encounter data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '78') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 31: Patient has immunizations data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 31 AS id, 'Patient has immunizations data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '81') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 32: Patient has insurance data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 32 AS id, 'Patient has insurance data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '84') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 33: Patient has labs data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 33 AS id, 'Patient has labs data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '87') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 34: Patient has medication_administrations data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 34 AS id, 'Patient has medication_administrations data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '90') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 35: Patient has microbiology data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 35 AS id, 'Patient has microbiology data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '93') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 36: Patient has nlp_biomarkers data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 36 AS id, 'Patient has nlp_biomarkers data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '96') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 37: Patient has nlp_drug_rationale data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 37 AS id, 'Patient has nlp_drug_rationale data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '99') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 38: Patient has nlp_measurement data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 38 AS id, 'Patient has nlp_measurement data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '102') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 39: Patient has nlp_sds data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 39 AS id, 'Patient has nlp_sds data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '105') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 40: Patient has nlp_sds_family data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 40 AS id, 'Patient has nlp_sds_family data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '108') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 41: Patient has observations data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 41 AS id, 'Patient has observations data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '111') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 42: Patient has patient_reported_medications data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 42 AS id, 'Patient has patient_reported_medications data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '114') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 43: Patient has prescriptions_written data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 43 AS id, 'Patient has prescriptions_written data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '117') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 44: Patient has procedure data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 44 AS id, 'Patient has procedure data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '120') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 45: Patient has visit data occurring data occurring 60 days after death event. Expected result: not dead
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 45 AS id, 'Patient has visit data occurring data occurring 60 days after death event. Expected result: not dead' AS description, 'Expect death' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.death WHERE person_id = '123') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 46: Test HCPCS derived device coming from procedure table
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 46 AS id, 'Test HCPCS derived device coming from procedure table' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.device_exposure WHERE person_id = '126' AND device_concept_id = '2614697' AND device_source_value = 'A4217') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 47: Test device derived from diagnosis table
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 47 AS id, 'Test device derived from diagnosis table' AS description, 'Expect device_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.device_exposure WHERE person_id = '127' AND device_concept_id = '45767866' AND device_source_value = 'Y73.0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 48: Patient has 1 valid MEDICATION_ADMINISTRATIONS record within the enrollment period.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 48 AS id, 'Patient has 1 valid MEDICATION_ADMINISTRATIONS record within the enrollment period.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '128' AND drug_exposure_start_date = '2011-01-07' AND drug_type_concept_id = '38000180' AND drug_source_value = '55111067101') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 49: Patient has 2 MEDICATION_ADMINISTRATIONS records, the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 49 AS id, 'Patient has 2 MEDICATION_ADMINISTRATIONS records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '129' AND drug_source_value = '55111067101') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 49 AS id, 'Patient has 2 MEDICATION_ADMINISTRATIONS records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '129' AND drug_source_value = '58487000102') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 50: Patient has multiple MEDICATION_ADMINISTRATIONS records, all within enrollment period, but have the same encounter_id, ndc and order_date.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 50 AS id, 'Patient has multiple MEDICATION_ADMINISTRATIONS records, all within enrollment period, but have the same encounter_id, ndc and order_date.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '130' AND drug_exposure_start_date = '2011-01-07' AND visit_occurrence_id = '131' AND drug_source_value = '55111067101') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 51: Patient has multiple MEDICATION_ADMINISTRATIONS records, all within enrollment period, that have the same ndc on the same day, but different encounters.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 51 AS id, 'Patient has multiple MEDICATION_ADMINISTRATIONS records, all within enrollment period, that have the same ndc on the same day, but different encounters.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '132') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 52: Patient has series of MEDICATION_ADMINISTRATIONS with the same encounter_id, but different order_date
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 52 AS id, 'Patient has series of MEDICATION_ADMINISTRATIONS with the same encounter_id, but different order_date' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '135') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 53: Patient has MEDICATION_ADMINISTRATIONS with provid that is NULL but the encounter has a valid provider id specified
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 53 AS id, 'Patient has MEDICATION_ADMINISTRATIONS with provid that is NULL but the encounter has a valid provider id specified' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '137' AND drug_exposure_start_date = '2012-01-08' AND provider_id = '139' AND visit_occurrence_id = '138') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 54: Patient has MEDICATION_ADMINISTRATIONS with an NDC that is properly mapped to the source_concept_id and standard concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 54 AS id, 'Patient has MEDICATION_ADMINISTRATIONS with an NDC that is properly mapped to the source_concept_id and standard concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '140' AND drug_concept_id = '1322189' AND drug_source_value = '55111067101' AND drug_source_concept_id = '45071548') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 55: Patient has MEDICATION_ADMINISTRATIONS with a valid quantity_of_dose
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 55 AS id, 'Patient has MEDICATION_ADMINISTRATIONS with a valid quantity_of_dose' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '141' AND quantity = '0.5') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 56: Patient has MEDICATION_ADMINISTRATIONS and the route value is found in the source-to-concept-map and assigned the proper concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 56 AS id, 'Patient has MEDICATION_ADMINISTRATIONS and the route value is found in the source-to-concept-map and assigned the proper concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '142' AND route_concept_id = '4128794' AND route_source_value = 'Oral') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 57: Patient has MEDICATION_ADMINISTRATIONS and the route value is NOT found in the source-to-concept-map and assigned concept_id of 0
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 57 AS id, 'Patient has MEDICATION_ADMINISTRATIONS and the route value is NOT found in the source-to-concept-map and assigned concept_id of 0' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '143' AND route_concept_id = '0' AND route_source_value = 'Osmosis') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 58: Patient has MEDICATION_ADMINISTRATIONS with a strength_unit that maps to dose_unit_source_value
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 58 AS id, 'Patient has MEDICATION_ADMINISTRATIONS with a strength_unit that maps to dose_unit_source_value' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '144' AND dose_unit_source_value = 'mg/mL') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 59: Patient has PRESCRIPTIONS_WRITTEN with valid information
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 59 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with valid information' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '145' AND drug_type_concept_id = '38000177') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 60: Patient has multiple PRESCRIPTIONS_WRITTEN with the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 60 AS id, 'Patient has multiple PRESCRIPTIONS_WRITTEN with the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '146') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 61: Patient has PRESCRIPTIONS_WRITTEN and the NDC is properly mapped to the source_concept_id and standard concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 61 AS id, 'Patient has PRESCRIPTIONS_WRITTEN and the NDC is properly mapped to the source_concept_id and standard concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '147' AND drug_concept_id = '1322189' AND drug_source_value = '55111067101' AND drug_source_concept_id = '45071548') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 62: Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains non-numeric values
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 62 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains non-numeric values' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '148' AND quantity = '90') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 63: Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains only numerics
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 63 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains only numerics' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '149' AND quantity = '90') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 64: Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains NULL AND quantity_of_dose is NOT NULL
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 64 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains NULL AND quantity_of_dose is NOT NULL' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '150' AND quantity = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 65: Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains NULL AND quantity_of_dose is NOT NULL with text
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 65 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains NULL AND quantity_of_dose is NOT NULL with text' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '151' AND quantity = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 66: Patient has PRESCRIPTIONS_WRITTEN with num_refils that contains only numerics
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 66 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with num_refils that contains only numerics' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '152' AND refills = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 67: Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains an empty value
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 67 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with quantity_per_fill that contains an empty value' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '153' AND refills = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 68: Patient has PRESCRIPTIONS_WRITTEN with days_supply that contains only numerics
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 68 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with days_supply that contains only numerics' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '154' AND days_supply = '1') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 69: Patient has PRESCRIPTIONS_WRITTEN with days_supply that contains an empty value
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 69 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with days_supply that contains an empty value' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '155' AND days_supply IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 70: Patient has PRESCRIPTIONS_WRITTEN with provid specified
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 70 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with provid specified' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '156' AND provider_id = '843801') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 71: Patient has PRESCRIPTIONS_WRITTEN with a route that is specified in the route source-to-concept map.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 71 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with a route that is specified in the route source-to-concept map.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '157' AND route_concept_id = '4128794' AND route_source_value = 'Oral') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 72: Patient has PRESCRIPTIONS_WRITTEN with strength + strength_unit + dose_frequency + dosage_form that should be concatenated
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 72 AS id, 'Patient has PRESCRIPTIONS_WRITTEN with strength + strength_unit + dose_frequency + dosage_form that should be concatenated' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '158' AND dose_unit_source_value = '20 - 25;15 MG;Capsule Delayed Release;1 time a day') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 73: Patient has patient_reported_medications with valid information
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 73 AS id, 'Patient has patient_reported_medications with valid information' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '159') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 74: Patient has multiple patient_reported_medications with the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 74 AS id, 'Patient has multiple patient_reported_medications with the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '160') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 75: Patient has patient_reported_medications with valid reported_date and drug_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 75 AS id, 'Patient has patient_reported_medications with valid reported_date and drug_type_concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '161' AND drug_exposure_start_date = '01-08-2012' AND drug_type_concept_id = '44787730') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 76: Patient has PRESCRIPTIONS_WRITTEN and the NDC is properly mapped to the source_concept_id and standard concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 76 AS id, 'Patient has PRESCRIPTIONS_WRITTEN and the NDC is properly mapped to the source_concept_id and standard concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '162' AND drug_concept_id = '1322189' AND drug_source_value = '55111067101' AND drug_source_concept_id = '45071548') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 77: Patient has patient_reported_medications with provid mapped
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 77 AS id, 'Patient has patient_reported_medications with provid mapped' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '163' AND provider_id = '179865') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 78: Patient has patient_reported_medications with a route that is specified in the route source-to-concept map.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 78 AS id, 'Patient has patient_reported_medications with a route that is specified in the route source-to-concept map.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '164' AND route_concept_id = '4128794' AND route_source_value = 'Oral') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 79: Patient has patient_reported_medications with a quantity_of_dose that maps to quantity.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 79 AS id, 'Patient has patient_reported_medications with a quantity_of_dose that maps to quantity.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '165' AND quantity = '6') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 80: Patient has immunizations with valid information
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 80 AS id, 'Patient has immunizations with valid information' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '166') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 81: Patient has multiple immunizations with the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 81 AS id, 'Patient has multiple immunizations with the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '167') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 82: Patient has multiple immunizations records, all within enrollment period, but have the same immunization_date and ndc
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 82 AS id, 'Patient has multiple immunizations records, all within enrollment period, but have the same immunization_date and ndc' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '168') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 83: Patient has immunizations with immunization_date that is NULL
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 83 AS id, 'Patient has immunizations with immunization_date that is NULL' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '169') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 84: Patient has immunizations with pt_reported =''Y''
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 84 AS id, 'Patient has immunizations with pt_reported =''Y''' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '170') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 85: Patient has immunizations and the NDC is properly mapped to the source_concept_id and standard concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 85 AS id, 'Patient has immunizations and the NDC is properly mapped to the source_concept_id and standard concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '171' AND drug_concept_id = '44818419' AND drug_source_value = '66521011710' AND drug_source_concept_id = '46255929') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 86: Patient has immunizations with pt_reported =''N'' with a valid drug_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 86 AS id, 'Patient has immunizations with pt_reported =''N'' with a valid drug_type_concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '172' AND drug_type_concept_id = '43542358') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 87: Procedure has PROC_CODE that is a drug with valid information and valid drug_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 87 AS id, 'Procedure has PROC_CODE that is a drug with valid information and valid drug_type_concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '173' AND drug_type_concept_id = '38000275') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 88: Patient has multiple PROCEDURE records with the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 88 AS id, 'Patient has multiple PROCEDURE records with the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '174') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 89: Patient has multiple PROCEDURE records, all within enrollment period, but have the same PROC_DATE and proc_code.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 89 AS id, 'Patient has multiple PROCEDURE records, all within enrollment period, but have the same PROC_DATE and proc_code.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '175') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 90: Patient has PROCEDURE with HCPCS proc_code that maps to a standard concept
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 90 AS id, 'Patient has PROCEDURE with HCPCS proc_code that maps to a standard concept' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '176' AND drug_concept_id = '43148859' AND drug_source_value = 'J9310' AND drug_source_concept_id = '2718907') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 91: Patient has PROCEDURE with provid_perform that maps to provid
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 91 AS id, 'Patient has PROCEDURE with provid_perform that maps to provid' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '177' AND drug_concept_id = '43148859' AND provider_id = '178' AND drug_source_value = 'J9310' AND drug_source_concept_id = '2718907') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 92: NLP_DRUG_RATIONALE has valid note_date and other valid information with a valid drug_type_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 92 AS id, 'NLP_DRUG_RATIONALE has valid note_date and other valid information with a valid drug_type_concept_id' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '179' AND drug_concept_id = '1310149' AND drug_exposure_start_date = '2011-01-07' AND drug_type_concept_id = '38000281' AND stop_reason = 'stop' AND visit_occurrence_id = '180' AND drug_source_value = 'COUMADIN') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 93: Patient has NLP_DRUG_RATIONALE with drug_action = STOP which should prevent it from being imported.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 93 AS id, 'Patient has NLP_DRUG_RATIONALE with drug_action = STOP which should prevent it from being imported.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '181') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 94: Patient has NLP_DRUG_RATIONALE with sentiment = NEED.NOT which should prevent it from being imported.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 94 AS id, 'Patient has NLP_DRUG_RATIONALE with sentiment = NEED.NOT which should prevent it from being imported.' AS description, 'Expect drug_exposure' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.drug_exposure WHERE person_id = '183') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 95: Simple Location
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 95 AS id, 'Simple Location' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.location WHERE location_source_value = 'REGION_DIVISION') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 96: No Location Dupes
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 96 AS id, 'No Location Dupes' AS description, 'Expect location' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.location WHERE location_source_value = 'DUPE_REGION_DUPE_DIVISION') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 97: When DIAGNOSIS_STATUS=Diagnosis Of and DIAGNOSIS_CD maps to DOMAIN=MEASUREMENT concept
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 97 AS id, 'When DIAGNOSIS_STATUS=Diagnosis Of and DIAGNOSIS_CD maps to DOMAIN=MEASUREMENT concept' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '187' AND measurement_concept_id = '4189544' AND measurement_date = '2009-01-01' AND measurement_source_value = '7953') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 98: When DIAGNOSIS_STATUS=Zachary and DIAGNOSIS_CD maps to DOMAIN=MEASUREMENT concept, should not write record
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 98 AS id, 'When DIAGNOSIS_STATUS=Zachary and DIAGNOSIS_CD maps to DOMAIN=MEASUREMENT concept, should not write record' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '189') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 99: When PRIMARY_DIAGNOSIS = 1 Then Type = 44786627
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 99 AS id, 'When PRIMARY_DIAGNOSIS = 1 Then Type = 44786627' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '191' AND measurement_type_concept_id = '44786627') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 100: When PRIMARY_DIAGNOSIS = 6 Then Type = 44786629
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 100 AS id, 'When PRIMARY_DIAGNOSIS = 6 Then Type = 44786629' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '193' AND measurement_type_concept_id = '44786629') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 101: MEASUREMENT_SOURCE_CONCEPT_ID for ICD9 795.3 gets mapped properly to 44828170
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 101 AS id, 'MEASUREMENT_SOURCE_CONCEPT_ID for ICD9 795.3 gets mapped properly to 44828170' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '195' AND measurement_source_concept_id = '44828170') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 102: When DIAGNOSIS_STATUS=Diagnosis Of and Source code is a SNOMED
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 102 AS id, 'When DIAGNOSIS_STATUS=Diagnosis Of and Source code is a SNOMED' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '197' AND measurement_concept_id = '4120300' AND measurement_date = '2009-01-01' AND measurement_source_value = '145003003') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 103: Test numeric result and SOURCE_CONCEPT_ID = 0
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 103 AS id, 'Test numeric result and SOURCE_CONCEPT_ID = 0' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '199' AND measurement_concept_id = '3027315' AND measurement_date = '2009-01-01' AND value_as_number = '100' AND measurement_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 104: Test non-numeric result and SOURCE_CONCEPT_ID = 0
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 104 AS id, 'Test non-numeric result and SOURCE_CONCEPT_ID = 0' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '201' AND measurement_concept_id = '3027315' AND measurement_date = '2009-01-01' AND value_as_number IS NULL AND value_as_concept_id = '45884084' AND measurement_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 105: Test valid operator gets an OPERATOR_CONCEPT_ID
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 105 AS id, 'Test valid operator gets an OPERATOR_CONCEPT_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '203' AND operator_concept_id = '4171754') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 106: Test invalid operator gets an OPERATOR_CONCEPT_ID
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 106 AS id, 'Test invalid operator gets an OPERATOR_CONCEPT_ID' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '205' AND operator_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 107: map case-sensitive UCUM vocabulary to UNIT_CONCEPT_ID, row count right
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 107 AS id, 'map case-sensitive UCUM vocabulary to UNIT_CONCEPT_ID, row count right' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '207' AND unit_concept_id = '8482') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 107 AS id, 'map case-sensitive UCUM vocabulary to UNIT_CONCEPT_ID, row count right' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '207') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 108: Test when normal range has a hyphen
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 108 AS id, 'Test when normal range has a hyphen' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '209' AND range_low = '55' AND range_high = '65') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 109: Test when normal range does not have a hyphen
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 109 AS id, 'Test when normal range does not have a hyphen' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '211' AND range_low IS NULL AND range_high IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 110: MEASUREMENT_TYPE gets properly mapped to a CONCEPT_ID from NLP_MEASUREMENT
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 110 AS id, 'MEASUREMENT_TYPE gets properly mapped to a CONCEPT_ID from NLP_MEASUREMENT' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '213' AND measurement_concept_id = '3025315' AND measurement_date = '2009-01-01' AND measurement_type_concept_id = '45754907' AND visit_occurrence_id = '214' AND measurement_source_value = 'WEIGHT' AND measurement_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 111: Non-numeric MEASUREMENT_VALUE from NLP_MEASUREMENT
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 111 AS id, 'Non-numeric MEASUREMENT_VALUE from NLP_MEASUREMENT' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '215' AND measurement_concept_id = '3025315' AND measurement_date = '2009-01-01' AND measurement_type_concept_id = '45754907' AND value_as_concept_id = '45884084' AND visit_occurrence_id = '216' AND measurement_source_value = 'WEIGHT' AND measurement_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 112: Measurement_detail gets mapped properly to a case sensitive UCUM from NLP_MEASUREMENT
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 112 AS id, 'Measurement_detail gets mapped properly to a case sensitive UCUM from NLP_MEASUREMENT' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '217' AND unit_concept_id = '8482' AND unit_source_value = 'pH') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 112 AS id, 'Measurement_detail gets mapped properly to a case sensitive UCUM from NLP_MEASUREMENT' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '217') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 113: Test that a mappable OBS_TYPE gets a CONCEPT_ID from OBSERVATIONS
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 113 AS id, 'Test that a mappable OBS_TYPE gets a CONCEPT_ID from OBSERVATIONS' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '219' AND measurement_concept_id = '3004249' AND measurement_date = '2009-01-01' AND measurement_type_concept_id = '45754907' AND measurement_source_value = 'SBP') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 114: Test that an unmappable OBS_TYPE gets a 0 CONCEPT_ID write a record to OBSERVATION table
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 114 AS id, 'Test that an unmappable OBS_TYPE gets a 0 CONCEPT_ID write a record to OBSERVATION table' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '221' AND observation_concept_id = '0' AND observation_source_value = 'Zach') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 115: Test UNIT_CONCEPT_ID gets mapped from OBSERVATIONS
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 115 AS id, 'Test UNIT_CONCEPT_ID gets mapped from OBSERVATIONS' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '223' AND unit_concept_id = '8482' AND unit_source_value = 'pH') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 115 AS id, 'Test UNIT_CONCEPT_ID gets mapped from OBSERVATIONS' AS description, 'Expect measurement' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.measurement WHERE person_id = '223') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 116: Tests if 2 patient durations (where second is subsumed by the first) results in a single observation period
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 116 AS id, 'Tests if 2 patient durations (where second is subsumed by the first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation_period WHERE person_id = '225') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 117: Tests if 2 patient durations (where second is within 30 days of first) results in a single observation period
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 117 AS id, 'Tests if 2 patient durations (where second is within 30 days of first) results in a single observation period' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation_period WHERE person_id = '226') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 118: Tests if 2 patient durations (where second starts 33 days after first) results in two observation periods
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 118 AS id, 'Tests if 2 patient durations (where second starts 33 days after first) results in two observation periods' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation_period WHERE person_id = '227') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 119: Patient duration is 1 month
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 119 AS id, 'Patient duration is 1 month' AS description, 'Expect observation_period' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation_period WHERE person_id = '228') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 120: Patient has 1 valid OBSERVATIONS record within the enrollment period. Validate that the obs_date maps to the observation_date field properly.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 120 AS id, 'Patient has 1 valid OBSERVATIONS record within the enrollment period. Validate that the obs_date maps to the observation_date field properly.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '229' AND observation_date = '2009-01-01') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 121: Patient has 2 OBSERVATIONS records, the first within the enrollment period, the second outside of enrollment.
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 121 AS id, 'Patient has 2 OBSERVATIONS records, the first within the enrollment period, the second outside of enrollment.' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '230') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 122: Patient has multiple OBSERVATIONS records, all within enrollment period
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 122 AS id, 'Patient has multiple OBSERVATIONS records, all within enrollment period' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '231') != 2 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 123: Patient has OBSERVATIONS record; validate the encid mapping to visit_occurrence_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 123 AS id, 'Patient has OBSERVATIONS record; validate the encid mapping to visit_occurrence_id' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.visit_occurrence WHERE visit_occurrence_id = '233' AND person_id = '232') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 124: Patient has OBSERVATIONS record; validate the obs_type mapping found in the STCM to observation_concept_id
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 124 AS id, 'Patient has OBSERVATIONS record; validate the obs_type mapping found in the STCM to observation_concept_id' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '234' AND observation_concept_id = '4052351') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 125: Patient has OBSERVATIONS record; validate the obs_type mapping NOT found in the STCM maps to observation_concept_id = 0
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 125 AS id, 'Patient has OBSERVATIONS record; validate the obs_type mapping NOT found in the STCM maps to observation_concept_id = 0' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '235' AND observation_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 126: Patient has OBSERVATIONS record; validate the observation_type_concept_id is populated correctly
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 126 AS id, 'Patient has OBSERVATIONS record; validate the observation_type_concept_id is populated correctly' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '236' AND observation_type_concept_id = '38000280') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 127: Patient has OBSERVATIONS record; validate the obs_time is mapped to observation_time
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 127 AS id, 'Patient has OBSERVATIONS record; validate the obs_time is mapped to observation_time' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '237' AND observation_datetime = '14:30:00') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 128: Patient has OBSERVATIONS record; validate the obs_result is mapped to value_as_number when obs_result can be cast to a numeric
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 128 AS id, 'Patient has OBSERVATIONS record; validate the obs_result is mapped to value_as_number when obs_result can be cast to a numeric' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '238' AND value_as_number = '100' AND value_as_string IS NULL) = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 129: Patient has OBSERVATIONS record; validate the obs_result is mapped to value_as_string when obs_result CANNOT be cast to a numeric
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 129 AS id, 'Patient has OBSERVATIONS record; validate the obs_result is mapped to value_as_string when obs_result CANNOT be cast to a numeric' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '239' AND value_as_number IS NULL AND value_as_string = 'One Hundred') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 130: Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND a valid unit_concept_id when it matches a concept in the UCUM vocabulary
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 130 AS id, 'Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND a valid unit_concept_id when it matches a concept in the UCUM vocabulary' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '240' AND unit_concept_id = '9529' AND unit_source_value = 'kilogram') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 131: Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND unit_concept_id = 0 when it matches a concept in the UCUM vocabulary
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 131 AS id, 'Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND unit_concept_id = 0 when it matches a concept in the UCUM vocabulary' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '241' AND unit_concept_id = '9529' AND unit_source_value = 'kg') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 132: Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND unit_concept_id = 0 when it does not match a standard concept in the UCUM vocabulary
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 132 AS id, 'Patient has OBSERVATIONS record; validate the obs_unit is mapped to unit_source_value AND unit_concept_id = 0 when it does not match a standard concept in the UCUM vocabulary' AS description, 'Expect observation' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.observation WHERE person_id = '242' AND unit_concept_id = '0' AND unit_source_value = 'TEST_UNIT') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 159: Tests Unknown gender does not get loaded
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 159 AS id, 'Tests Unknown gender does not get loaded' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '295') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 160: Tests Male gender
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 160 AS id, 'Tests Male gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '296' AND gender_concept_id = '8507' AND year_of_birth = '1950') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 161: Tests Female gender
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 161 AS id, 'Tests Female gender' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '297' AND gender_concept_id = '8532' AND year_of_birth = '1950') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 162: Tests Unknown birth year
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 162 AS id, 'Tests Unknown birth year' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '298') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 163: Tests 1927 and earlier birth year
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 163 AS id, 'Tests 1927 and earlier birth year' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '299' AND gender_concept_id = '8507' AND year_of_birth = '1927') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 164: Tests 1930 birth year
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 164 AS id, 'Tests 1930 birth year' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '300' AND gender_concept_id = '8507' AND year_of_birth = '1930') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 165: Tests Asian race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 165 AS id, 'Tests Asian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '301' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8515' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 166: Tests African American race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 166 AS id, 'Tests African American race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '302' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8516' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 167: Tests Caucasian race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 167 AS id, 'Tests Caucasian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '303' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8527' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 168: Tests Unknown race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 168 AS id, 'Tests Unknown race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '304' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '0' AND ethnicity_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 169: Tests Hispanic ethnicity, Asian race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 169 AS id, 'Tests Hispanic ethnicity, Asian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '305' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8515' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 170: Tests Hispanic ethnicity, African American race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 170 AS id, 'Tests Hispanic ethnicity, African American race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '306' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8516' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 171: Tests Hispanic ethnicity, Caucasian race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 171 AS id, 'Tests Hispanic ethnicity, Caucasian race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '307' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '8527' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 172: Tests Hispanic ethnicity, unknown race
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 172 AS id, 'Tests Hispanic ethnicity, unknown race' AS description, 'Expect person' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.person WHERE person_id = '308' AND gender_concept_id = '8507' AND year_of_birth = '1950' AND race_concept_id = '0' AND ethnicity_concept_id = '38003563') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 173: Tests procedure record with proc_code_type CPT4
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 173 AS id, 'Tests procedure record with proc_code_type CPT4' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '309' AND procedure_concept_id = '2108115' AND procedure_source_value = '36415') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 174: Tests procedure record with proc_code_type HCPCS
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 174 AS id, 'Tests procedure record with proc_code_type HCPCS' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '310' AND procedure_concept_id = '43533247' AND procedure_source_value = 'G0290') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 175: Tests procedure record with proc_code_type ICD9
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 175 AS id, 'Tests procedure record with proc_code_type ICD9' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '311' AND procedure_concept_id = '2001373' AND procedure_source_value = '33.50') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 176: Tests procedure record with proc_code_type ICD10
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 176 AS id, 'Tests procedure record with proc_code_type ICD10' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '312' AND procedure_concept_id = '2755024' AND procedure_source_value = '0J8S0ZZ') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 177: Tests procedure type concept
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 177 AS id, 'Tests procedure type concept' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '313' AND procedure_type_concept_id = '38000275') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 178: Tests procedure record with proc_code_type of blank results in unmapped procedure occurrence
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 178 AS id, 'Tests procedure record with proc_code_type of blank results in unmapped procedure occurrence' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '314' AND procedure_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 179: Tests procedure record with proc_code_type CUSTOM results in unmapped procedure occurrence
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 179 AS id, 'Tests procedure record with proc_code_type CUSTOM results in unmapped procedure occurrence' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '315' AND procedure_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 180: Tests procedure record with proc_code_type REV results in unmapped procedure occurrence
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 180 AS id, 'Tests procedure record with proc_code_type REV results in unmapped procedure occurrence' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '316' AND procedure_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 181: Tests procedure record with proc_code_type CLM_UNK results in unmapped procedure occurrence
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 181 AS id, 'Tests procedure record with proc_code_type CLM_UNK results in unmapped procedure occurrence' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '317' AND procedure_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 182: Tests procedure type concept id from diagnosis record
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 182 AS id, 'Tests procedure type concept id from diagnosis record' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '318' AND procedure_type_concept_id = '42865906') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 183: Diagnosis without ''Diagnosis of'' status is not loaded
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 183 AS id, 'Diagnosis without ''Diagnosis of'' status is not loaded' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '320') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 184: Diagnosis record with diagnosis_cd_type ICD9
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 184 AS id, 'Diagnosis record with diagnosis_cd_type ICD9' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '322' AND procedure_concept_id = '40491846' AND procedure_source_value = '7946') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 185: Diagnosis record with diagnosis_cd_type ICD10
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 185 AS id, 'Diagnosis record with diagnosis_cd_type ICD10' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '324' AND procedure_concept_id = '4180938' AND procedure_source_value = 'R93.9') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 186: Diagnosis record with diagnosis_cd_type SNOMED
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 186 AS id, 'Diagnosis record with diagnosis_cd_type SNOMED' AS description, 'Expect procedure_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.procedure_occurrence WHERE person_id = '326' AND procedure_concept_id = '4001760' AND procedure_source_value = '10019001') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 187: Simple Provider Mapping
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 187 AS id, 'Simple Provider Mapping' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.provider WHERE specialty_concept_id = '38004456' AND specialty_source_value = 'Internal Medicine' AND specialty_source_concept_id = '0') = 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 188: Dupe Provider Mapping
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 188 AS id, 'Dupe Provider Mapping' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.provider WHERE specialty_concept_id = '38004453' AND specialty_source_value = 'Family Medicine' AND specialty_source_concept_id = '0') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 189: Non-Primary specialty Mapping
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 189 AS id, 'Non-Primary specialty Mapping' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.provider WHERE specialty_source_value = 'Primary Medicine') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 189 AS id, 'Non-Primary specialty Mapping' AS description, 'Expect provider' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.provider WHERE specialty_source_value = 'Emergency Medicine') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
-- 190: Visit from Diagnosis Test
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 190 AS id, 'Visit from Diagnosis Test' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.visit_occurrence WHERE person_id = '331' AND visit_start_date = '2014-03-05' AND visit_end_date = '2014-03-10') != 1 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 190 AS id, 'Visit from Diagnosis Test' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.visit_occurrence WHERE person_id = '331' AND visit_start_date = '2014-03-06') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;
INSERT INTO testing.cdm_testing_optumpan.test_results SELECT 190 AS id, 'Visit from Diagnosis Test' AS description, 'Expect visit_occurrence' AS test, CASE WHEN (SELECT COUNT(*) FROM testing.cdm_testing_optumpan.visit_occurrence WHERE person_id = '331' AND visit_start_date = '2014-03-07') != 0 THEN 'FAIL' ELSE 'PASS' END AS status;