SELECT DISTINCT lower(SOURCE_CODE) SOURCE_CODE, TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP
where source_vocabulary_ID = 500
union all
SELECT DISTINCT upper(SOURCE_CODE) SOURCE_CODE, TARGET_CONCEPT_ID
FROM SOURCE_TO_CONCEPT_MAP
where source_vocabulary_ID = 500