{Source_to_Standard}
SELECT distinct LOWER(SOURCE_CODE), TARGET_CONCEPT_ID, TARGET_DOMAIN_ID
FROM CTE_VOCAB_MAP
WHERE lower(SOURCE_VOCABULARY_ID) IN ('jnj_tru_hra_question')
AND (TARGET_INVALID_REASON IS NULL or TARGET_INVALID_REASON = '')
union all
SELECT distinct UPPER(SOURCE_CODE), TARGET_CONCEPT_ID, TARGET_DOMAIN_ID
FROM CTE_VOCAB_MAP
WHERE lower(SOURCE_VOCABULARY_ID) IN ('jnj_tru_hra_question')
AND (TARGET_INVALID_REASON IS NULL or TARGET_INVALID_REASON = '')