/*CCAE Sprint 6 Test Cases Table 9 Procedure Occurrence*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their procedures will not come through*/

/*901*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 901,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*902*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	902,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*903*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	903,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*904*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	904,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*905*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 905,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*906*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	906,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*907*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	907,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*908*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1983,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	908,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)

/*Insert values into inpatient_services, outpatient_Services, facility_header and inpatient_admissions to create procedure_occurrence records*/

/*901*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 9011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 901, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, N'65779', NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-06-11' as Date), NULL, Cast('2012-06-12' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES       (NULL, NULL, NULL, NULL, 9011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 901, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'29914', NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL)

/*902*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 9021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 902, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, N'50760', NULL, NULL, 1234567, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, 220, Cast('2012-10-20' as Date), NULL, Cast('2012-10-22' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES        (NULL, NULL, NULL, NULL, NULL, 9021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 902, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, N'50760', NULL, NULL, 3456789, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, 540, Cast('2012-10-20' as Date), NULL, Cast('2012-10-22' as Date), NULL, NULL, 2012, NULL, NULL)

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG)
VALUES       (NULL, NULL, NULL, NULL, 9021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 902, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL)

/*903*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 903, 4567, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'54861', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-02-15' as Date), 
                         NULL, Cast('2012-02-15' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9031, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 903, 4567, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'54861', NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-02-15' as Date), Cast('2012-02-15' as Date), NULL, NULL, 2012, NULL)

/*904*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 904, 5678, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-03-03' as Date), 
                         NULL, Cast('2012-03-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9041, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 904, 5678, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'93042', NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-03-03' as Date), Cast('2012-03-03' as Date), NULL, NULL, 2012, NULL)

/*905*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 905, 6789, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'E0636', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-04-03' as Date), 
                         NULL, Cast('2012-04-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9051, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 905, 6789, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-04-03' as Date), Cast('2012-04-03' as Date), NULL, NULL, 2012, NULL)

/*906*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 906, 7890, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'90686', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-05-03' as Date), 
                         NULL, Cast('2012-05-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9061, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 906, 7890, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-05-03' as Date), Cast('2012-05-03' as Date), NULL, NULL, 2012, NULL)

/*907*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 907, 8901, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'82985', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-06-03' as Date), 
                         NULL, Cast('2012-06-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9071, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 907, 8901, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-06-03' as Date), Cast('2012-06-03' as Date), NULL, NULL, 2012, NULL)

/*908*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 908, 9012, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, N'S9368', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-07-03' as Date), 
                         NULL, Cast('2012-07-03' as Date), NULL, NULL, 2012, NULL)

INSERT [dbo].[FACILITY_HEADER] (AGE, AGEGRP, BILLTYP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DSTATUS, DX1, DX2, DX3, DX4, DX5, DX6, 
                         DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, 
                         NTWKPROV, PAIDNTWK, PDDATE, PHYFLAG, PLANKEY, PLANTYP, PROC1, PROC2, PROC3, PROC4, PROC5, PROC6, PROVID, REGION, RX, SEQNUM, SEX, 
                         STDPLAC, STDPROV, SVCDATE, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID)
VALUES        (NULL, NULL, NULL, NULL, 9081, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 908, 9012, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, Cast('2012-07-03' as Date), Cast('2012-07-03' as Date), NULL, NULL, 2012, NULL)

/*Check*/
SELECT * FROM INPATIENT_SERVICES WHERE ENROLID LIKE '9%'
SELECT * FROM OUTPATIENT_SERVICES WHERE ENROLID LIKE '9%'
SELECT * FROM INPATIENT_ADMISSIONS WHERE ENROLID LIKE '9%'
SELECT * FROM FACILITY_HEADER WHERE ENROLID LIKE '9%'