/*CCAE Sprint 6 Test Cases Table 8 Condition Era*/

/*Patients must be entered in the enrollment details table first so we know that they have valid observation periods. Otherwise
they will be dropped if the builder does not see that they have prescription benefits and their condition eras will not come through*/

/*801*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL, NULL, NULL, 1980, Cast(N'2012-12-31' as Date),	Cast (N'2012-01-01' as Date), NULL, NULL, N'11', NULL, 801,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, NULL,	NULL, N'1',	NULL, N'1',	NULL, NULL, NULL, NULL)
/*802*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1981,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	802,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'2',	NULL,	NULL,	NULL,	NULL)
/*803*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	803,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)
/*804*/
INSERT [dbo].[ENROLLMENT_DETAIL] ([AGE], [AGEGRP], [DATATYP], [DOBYR], [DTEND], [DTSTART], [EECLASS], [EESTATU], [EGEOLOC], [EMPREL], [ENROLID], [HLTHPLAN], [INDSTRY], [MEMDAYS], [MHSACOVG], [MSA], [PHYFLAG], [PLANKEY], [PLANTYP], [REGION], [RX], [SEQNUM], [SEX], [VERSION], [WGTKEY], [EFAMID], [YEAR]) VALUES (NULL,	NULL,	NULL,	1982,	Cast (N'2012-12-31' as Date),	Cast (N'2012-1-1' as Date),	NULL,	NULL,	N'11',	NULL,	804,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	NULL,	N'1',	NULL,	N'1',	NULL,	NULL,	NULL,	NULL)

/*Insert values into inpatient_services, outpatient_Services, facility_header and inpatient_admissions to create condition_era records (condition_occurrence records will also be created by default)*/

/*801*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, 8011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 801, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  N'71978', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-04-21' as Date), NULL, Cast('2012-04-22' as Date), NULL, NULL, 2012, NULL, NULL, N'9')

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG, DXVER)
VALUES       (NULL, NULL, NULL, NULL, 8011, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 801, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL, N'9')

/*802*/
INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, 8021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'37613', NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 802, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-07-01' as Date), NULL, Cast('2012-07-02' as Date), NULL, NULL, 2012, NULL, NULL, N'9')

INSERT [dbo].[INPATIENT_SERVICES] (ADMDATE, ADMTYP, AGE, AGEGRP, CAP_SVC, CASEID, COB, COINS, COPAY, DATATYP, DEDUCT, DISDATE, DOBYR, DSTATUS, DX1, DX2,
                          DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, 
                         NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, PDX, PHYFLAG, PLANKEY, PLANTYP, PPROC, PROC1, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, 
                         RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DRG, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, 8021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, N'37613', NULL, 
						  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 802, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL,  NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,
                          NULL, NULL, NULL, NULL, NULL, Cast('2012-07-12' as Date), NULL, Cast('2012-07-14' as Date), NULL, NULL, 2012, NULL, NULL, N'9')

INSERT [dbo].[INPATIENT_ADMISSIONS] (ADMDATE, ADMTYP, AGE, AGEGRP, CASEID, DATATYP, DAYS, DISDATE, DOBYR, DSTATUS, DX1, DX10, DX11, DX12, DX13, DX14, 
                         DX15, DX2, DX3, DX4, DX5, DX6, DX7, DX8, DX9, EECLASS, EESTATU, EGEOLOC, EIDFLAG, EMPREL, ENRFLAG, ENROLID, HLTHPLAN, HOSPNET, HOSPPAY, 
                         INDSTRY, MDC, MHSACOVG, MSA, PDX, PHYFLAG, PHYSID, PHYSNET, PHYSPAY, PLANKEY, PLANTYP, PPROC, PROC1, PROC10, PROC11, PROC12, PROC13, 
                         PROC14, PROC15, PROC2, PROC3, PROC4, PROC5, PROC6, PROC7, PROC8, PROC9, REGION, RX, SEQNUM, SEX, STATE, TOTCOB, TOTCOINS, TOTCOPAY, 
                         TOTDED, TOTNET, TOTPAY, VERSION, WGTKEY, YEAR, EFAMID, DRG, DXVER)
VALUES       (NULL, NULL, NULL, NULL, 8021, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 802, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, 2012, NULL, NULL, N'9')

/*803*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  N'28260', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 803, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-01-22' as Date), 
                         NULL, Cast('2012-01-22' as Date), NULL, NULL, 2012, NULL, N'9')

INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  N'28260', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 803, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-09-24' as Date), 
                         NULL, Cast('2012-09-24' as Date), NULL, NULL, 2012, NULL, N'9')
/*804*/
INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  N'F1675', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 804, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-01-22' as Date), 
                         NULL, Cast('2012-01-22' as Date), NULL, NULL, 2012, NULL, N'0')

INSERT [dbo].[OUTPATIENT_SERVICES] (AGE, AGEGRP, CAP_SVC, COB, COINS, COPAY, DATATYP, DEDUCT, DOBYR, DX1, DX2, DX3, DX4, DX5, EECLASS, EESTATU, EGEOLOC, 
                         EIDFLAG, EMPREL, ENRFLAG, ENROLID, FACHDID, FACPROF, HLTHPLAN, INDSTRY, MDC, MHSACOVG, MSA, NETPAY, NTWKPROV, PAIDNTWK, PAY, PDDATE, 
                         PHYFLAG, PLANKEY, PLANTYP, PROC1, PROCGRP, PROCMOD, PROCTYP, PROVID, QTY, REGION, REVCODE, RX, SEQNUM, SEX, STDPLAC, STDPROV, SVCDATE, 
                         SVCSCAT, TSVCDAT, VERSION, WGTKEY, YEAR, EFAMID, DXVER)
VALUES        (NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL,  N'F1675', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, 804, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 
                         NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, Cast('2012-02-02' as Date), 
                         NULL, Cast('2012-02-02' as Date), NULL, NULL, 2012, NULL, N'0')

/*Check*/
SELECT * FROM INPATIENT_SERVICES WHERE ENROLID LIKE '8%'
SELECT * FROM OUTPATIENT_SERVICES WHERE ENROLID LIKE '8%'


				